### ISSUE TITLE
openvpn-resin not autostarted in flasher --resinio builds

### ISSUE THREAD

**Issue by floion** [resin-os/resinos#104]
# systemctl status openvpn-resin

 openvpn-resin.service - OpenVPN Application On Resin
   Loaded: loaded (/lib/systemd/system/openvpn-resin.service; enabled; vendor preset: enabled)
   Active: inactive (dead)

**Comment by floion** [comment]
openvpn-resin is now part of resin.target

But on flasher images:

# systemctl status resin.target -l
 resin.target
   Loaded: not-found (Reason: No such file or directory)
   Active: inactive (dead)

**Comment by floion** [comment]
So @agherzan do we want this in flasher or we remove vpn from flasher altogether?

**Comment by floion** [comment]
Repinging on this @agherzan

**Comment by floion** [comment]
cc @petrosagg

**Comment by agherzan** [comment]
@floion Sorry for being late in a reply here. After rethinking a little bit, I think having it in flasher would be a good idea on the long term in the case we will need additional information in the dashboard. So let's fix it by enabling it in flasher images too (as we used to have it).

**Comment by floion** [comment]
@agherzan should we consider this for resinOS 2.0 milestone?

**Comment by agherzan** [comment]
Yes. Thanks @floion
