### ISSUE TITLE
Update ALL the links to use /resinos/ folder

### ISSUE THREAD

**Issue by emirotin** [resin-os/resinos#106]
Like `https://files.resin.io/images/raspberry-pi/2.0.0-beta.1/resin-dev.zip` -> `https://files.resin.io/resinos/raspberry-pi/2.0.0-beta.1/resin-dev.zip`

Then coordinate with Heds when to redeploy the site.

**Comment by lurch** [comment]
It would be great if #12 could be fixed at the same time ;-)

**Comment by hedss** [comment]
All files now moved to new location.

**Comment by emirotin** [comment]
@lurch not at the same time I'm afraid :) But I feel your pain. #12 needs more thinking though.
