### ISSUE TITLE
Upgrade to yocto morty version

### ISSUE THREAD

**Issue by agherzan** [resin-os/resinos#113]
We are currently basing our linux host OS on yocto jethro. This task should bring all the boards to yocto morty.

Ref.: https://wiki.yoctoproject.org/wiki/Releases

**Comment by floion** [comment]
As a first step, I will update them to krogoth. Just so we are up to date. And then inspect which boards have the BSPs on morty, and which are problematic

**Comment by floion** [comment]
@agherzan meta-ti [http://git.yoctoproject.org/git/meta-ti] has no morty branch

**Comment by agherzan** [comment]
@floion I know ti uses branch late strategy for releasing new branches. I would suspect that master would work just fine.

**Comment by shaunmulligan** [comment]
Should include https://github.com/resin-os/resinos/issues/154

**Comment by floion** [comment]
fixed by https://github.com/resin-os/meta-resin/pull/543 and https://github.com/resin-os/meta-resin/pull/523

**Comment by agherzan** [comment]
All the boards board release 2.0 are on morty (or closest to morty possible based on BSP support). Moving this out of the milestone as there are still old boards not updated yet.

**Comment by agherzan** [comment]
Closing this issue as all the boards we had in plan for 2.0 are on morty or the latest supported version by the BSP.

**Comment by agherzan** [comment]
Reopening as qemu device types are planed for morty update too,

**Comment by willnewton** [comment]
resin-qemu was upgraded by https://github.com/resin-os/resin-qemu/pull/50
