### ISSUE TITLE
Deploy a jenkins server for BSP yocto layers we currently maintain 

### ISSUE THREAD

**Issue by agherzan** [resin-os/resinos#121]

**Comment by agherzan** [comment]
@brownjohnf After a discussion with @petrosagg we decided to have:
yocto.resin.io (landing page - similar to resinos.io)
yocto-ci.resin.io (jenkins web interface)

**Comment by brownjohnf** [comment]
Cool, I like it. I'll let you know when it's up.

**Comment by agherzan** [comment]
Hi @brownjohnf . Any updates on this one?

**Comment by brownjohnf** [comment]
Sorry @agherzan, I've gotten caught up by other things. I'll prioritize this for mon morning. The host is up, I just need to get Jenkins installed.

**Comment by agherzan** [comment]
It was done and it's not available at https://yocto-ci.resin.io/.
