### ISSUE TITLE
2.x: Device becomes out of space after 3 updates

### ISSUE THREAD

**Issue by shaunmulligan** [resin-os/resinos#125]
Device type: TS4900
resinOS version: Resin OS 2.0.0-beta.2
supevisor: 2.7.1

**error in dashboard**
After third update we got 

>failed: Error applying device configuration: Error: update "deviceConfig" set "targetValues" = '{"RESIN_SUPERVISOR_DELTA":"1"}' - SQLITE_FULL: database or disk is full

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_t1z)

**Comment by agherzan** [comment]
@shaunmulligan we need a testing image with which we can reproduce the problem.

**Comment by shaunmulligan** [comment]
@agherzan we now have their dockerfile (attached in front thread), so we need to assign someone to investigate.

**Comment by agherzan** [comment]
Yes @shaunmulligan . @josephroberts is working on this.

**Comment by agherzan** [comment]
@josephroberts what happened to this bug?

**Comment by josephroberts** [comment]
@agherzan I spent a long time trying to repro and was never able to. There are some notes in the front thread.

**Comment by shaunmulligan** [comment]
I believe this most likely has been resolved by new changes in the supervisor 3.x version as new fixes for deltas on AUFS were added.

**Comment by agherzan** [comment]
I will close this as @josephroberts was not able to reproduce.
