### ISSUE TITLE
ResinOS 2.x: Image size investigation

### ISSUE THREAD

**Issue by telphan** [resin-os/resinos#126]
We are going to  have 2 boot partitions (the same way we have 2 root partitions). BootPart2 is the size of the second boot partition (the new one). Boot partition size will not vary between device types. The following will be implemented:
`BootPart2_Size = BootPart1_Size` 
The root partition will vary between device types, as there big differences between BSPs and some device types pay hefty architecture size penalties. We will also add a size buffer of 50Mb. The following will be implemented:
` Rootfs_Size = BSP_Size + NonBSP_Size + Buffer(50Mb)*Arch_Penalty` 

The way we calcultate the full image size can be seen below:
`Image_Size = 2*BootPart_Size + 2*Rootfs_Size + 20Mb + 2*4Mb`

https://docs.google.com/a/resin.io/spreadsheets/d/1B4Vz-d3bSYW3O3fHEUs9FcML-wiv2hd4O0cxwnEG3oo/edit?usp=sharing

**Comment by agherzan** [comment]
@telphan To set a call with @petrosagg @shaunmulligan me and @alexandrosm .

**Comment by telphan** [comment]
As per our last conversation:
The raspberry pi family will receive another boot partition.
Every device type will have the total OS size (i.e. boots + rootfs + conf) sed to 600Mb

**Comment by floion** [comment]
What is the status on this? Is there a document somewhere that should be the source of all truth with regards to resinos partition layout?

**Comment by agherzan** [comment]
meta-resin implemented with 700 total resin space taken for all the boards supported.
