### ISSUE TITLE
The MAC address for the WiFi chipset on the BeagleBone Green Wireless is always DE:AD:BE:EF:00:00

### ISSUE THREAD

**Issue by floion** [resin-os/resinos#133]
https://gist.github.com/theojulienne/9251b79bcbd68b4e9240

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_w3k)

**Comment by floion** [comment]
@agherzan please distribute this in the team

**Comment by willnewton** [comment]
I'm not sure the linked fix is valid. It sets the MAC on my BBGW to D0:B5:C2:C1:FD:0D (stable across reboot) but does not match the MAC printed on the sticker on the board 2C:F7:F1:06:26:40. It seems like to do this we might need a more involved solution such as:

https://github.com/rcn-ee/repos/blob/master/bb-wl18xx-firmware/suite/jessie/debian/bb-wl18xx-wlan0
