### ISSUE TITLE
Repeated disconnects with edison board

### ISSUE THREAD

**Issue by CameronDiver** [resin-os/resinos#139]
ResinOS v1.22.1 
Provisioned fine, then kept disconnecting at the dashboard, sometimes reconnecting itself, other times needing a restart.

Tested with three separate edisons and two base boards.

**Comment by floion** [comment]
Did you happen to have a serial connection to the board? Was it just disconnecting or the board was frozen?

**Comment by shaunmulligan** [comment]
A similar issue was seen on the hummingboard v1.24, here the device would come online for a few minutes and then drop offline.

**Comment by CameronDiver** [comment]
@floion No serial connection, just a completely standard provision and push

**Comment by agherzan** [comment]
@floion can you link this to the PR please?

**Comment by floion** [comment]
@CameronDiver this has been fixed and released to production
Can you please test it again?
Thanks

**Comment by CameronDiver** [comment]
@floion Seems to be working for me, did a provision, pushed code and checked pub url was working - All fine.

**Comment by floion** [comment]
Great. We can close the issue then.
Thanks
