### ISSUE TITLE
Broken link in gettingstarted.md

### ISSUE THREAD

**Issue by lurch** [resin-os/resinos#14]
The "rdt docs" link currently doesn't go anywhere.
I tracked down https://github.com/resin-os/resin-device-toolbox but that doesn't appear to have any docs (yet) either.

**Comment by shaunmulligan** [comment]
@lurch thanks for spotting that, and apologies for not having docs on `rdt` yet, I guess for now we should probably point that link to https://resinos.io/docs/architecture/#resin-device-toolbox 

Also @lekkas we should at least add a bit of documentation on the README.md of resin-device-toolbox repo.

**Comment by lurch** [comment]
> Also @lekkas we should at least add a bit of documentation on the README.md of resin-device-toolbox repo.

Yeah, https://www.npmjs.com/package/resin-device-toolbox is currently complaining about no README ;-)

**Comment by lekkas** [comment]
@lurch @shaunmulligan - added README.md : https://github.com/resin-os/resin-device-toolbox/blob/master/README.md
