### ISSUE TITLE
ts4900 reboots after shutdown

### ISSUE THREAD

**Issue by agherzan** [resin-os/resinos#145]
Board shutdown but if no further action is taken, after a minute or so the board is booted again and the flashing procedure is hence restarted.

**Comment by floion** [comment]
Board shutsdown but if no further action is taken, after a minute or so the board is booted again and the flashing procedure is hence restarted.

**Comment by floion** [comment]
[  255.445930] BTRFS: device label resin-data devid 1 transid 19 /dev/mmcblk2p6
[  267.402323] systemd-shutdown[1]: Sending SIGTERM to remaining processes...
[  267.430265] systemd-journald[201]: Received SIGTERM from PID 1 (systemd-shutdow).
[  267.465837] systemd-shutdown[1]: Sending SIGKILL to remaining processes...
[  267.490983] systemd-shutdown[1]: Unmounting file systems.
[  267.497547] systemd-shutdown[1]: Unmounting /mnt/boot.
[  267.545407] systemd-shutdown[1]: Unmounting /mnt/bootorig.
[  267.595647] systemd-shutdown[1]: Unmounting /var/volatile.
[  267.636909] systemd-shutdown[1]: Unmounting /tmp.
[  267.743521] systemd-shutdown[1]: All filesystems unmounted.
[  267.749305] systemd-shutdown[1]: Deactivating swaps.
[  267.754660] systemd-shutdown[1]: All swaps deactivated.
[  267.760066] systemd-shutdown[1]: Detaching loop devices.
[  267.774453] systemd-shutdown[1]: All loop devices detached.
[  267.780108] systemd-shutdown[1]: Detaching DM devices.
[  267.785688] systemd-shutdown[1]: All DM devices detached.
[  267.797884] systemd-shutdown[1]: Powering off.
[  267.819875] imx2-wdt 20bc000.wdog: Device shutdown: Expect reboot!
[  267.826272] reboot: System halted

**Comment by agherzan** [comment]
Fixed in https://github.com/resin-os/resin-ts/pull/60, https://github.com/resin-os/resin-ts/pull/59
