### ISSUE TITLE
User can't provision the Intel NUC skull canyon

### ISSUE THREAD

**Issue by shaunmulligan** [resin-os/resinos#149]
User tried to provision a new NUC skull canyon,  it appeared on the dashboard in flashing mode, but seems like it can't flash to internal media, so it just sat there forever.

@floion or @agherzan , do either of you have one of these devices? I think 2 or  3 people have raised this recently

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_wgq)

**Comment by floion** [comment]
Yes, I have tested the Intel NUC6i7KYK on my side and tests passed.
I have let the user know we released a new version so he can test and come back to us.
I suspect that his particular NUC model is using nvme storage and on my end I do not have that type of storage to test with.

**Comment by floion** [comment]
Still pending user reply

**Comment by agherzan** [comment]
Took this and will implement NVME support.

**Comment by agherzan** [comment]
NVME support was merged so we can close this.
