### ISSUE TITLE
Flasher image systemd services ordering issue (observed on a beaglebone black, with host OS version 1.24.0)

### ISSUE THREAD

**Issue by floion** [resin-os/resinos#153]
Due to this, the flashing process does not start.

[    5.341790] systemd[1]: mnt-boot.mount: Found ordering cycle on mnt-boot.mount/start                                                                                                                                                      
[    5.349621] systemd[1]: mnt-boot.mount: Found dependency on mnt-bootorig-config.json.mount/start                                                                                                                                          
[    5.358477] systemd[1]: mnt-boot.mount: Found dependency on temp-conf.service/start                                                                                                                                                       
[    5.366190] systemd[1]: mnt-boot.mount: Found dependency on basic.target/start                                                                                                                                                            
[    5.373463] systemd[1]: mnt-boot.mount: Found dependency on paths.target/start                                                                                                                                                            
[    5.380734] systemd[1]: mnt-boot.mount: Found dependency on systemd-ask-password-console.path/start                                                                                                                                       
[    5.389840] systemd[1]: mnt-boot.mount: Found dependency on plymouth-start.service/start                                                                                                                                                  
[    5.397982] systemd[1]: mnt-boot.mount: Found dependency on mnt-boot.mount/start                                                                                                                                                          
[    5.405429] systemd[1]: mnt-boot.mount: Breaking ordering cycle by deleting job mnt-bootorig-config.json.mount/start                                                                                                                      
[    5.416019] systemd[1]: mnt-bootorig-config.json.mount: Job mnt-bootorig-config.json.mount/start deleted to break ordering cycle starting with mnt-boot.mount/start                                                                       
[ SKIP ] Ordering cycle found, skipping Flasher conf partition mountpoint

**Comment by agherzan** [comment]
Fix implemented only on 1.X as on 2.X this issue seems to not be reproducible - tested by @michal-mazurek .
