### ISSUE TITLE
Upgrade raspberry pi kernel to 4.4.x

### ISSUE THREAD

**Issue by shaunmulligan** [resin-os/resinos#154]
<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_xhu)

**Comment by shaunmulligan** [comment]
linked to: https://github.com/resin-os/resinos/issues/113

**Comment by agherzan** [comment]
Done as part of https://github.com/resin-os/resin-raspberrypi/pull/76
