### ISSUE TITLE
The yocto automation script should push to our registry too (v1)

### ISSUE THREAD

**Issue by agherzan** [resin-os/resinos#155]
https://github.com/resin-os/resin-yocto-scripts/blob/master/automation/jenkins_build.sh#L144

Devices prior 1.1.5 can't pull from registry v2. Resinhup has already the functionality to try to pull from our v1 registry in this case so we will need to automatically push the images to our registry (staging) too with every new production release. In this way old device will be having at their disposal resinos images in our registry automatically (exactly the way we do it for dockerhub).

PS: After implementing this, we will need to update all the submodules in `resin-<board>` repositories too. So make sure you create PRs for those as well linking them to this issue.

PS: Make sure jenkins has permissions to push to our registry too.

**Comment by michal-mazurek** [comment]
The change to jenkins_build.sh is now being tested on resin-edison.

**Comment by agherzan** [comment]
Waiting for @floion to test a release on edison an then we will update all the resin-<board> repository with the new revision of resin-yocto-scripts and do the required jenkins modifications.

**Comment by floion** [comment]
@michal-mazurek can you confirm this is fixed now and can be closed?

**Comment by michal-mazurek** [comment]
This is now deployed everywhere and so far no complaints.
