### ISSUE TITLE
Serial console is enabled by default on Rpi/Rpi3 but shouldn't be

### ISSUE THREAD

**Issue by hedss** [resin-os/resinos#156]
Using the stock images from [here](https://resinos.io/#downloads-raspberrypi), both the Raspberry Pi and Raspberry Pi 3 images appear to have serial console enabled by default.

From this [Flowdock thread](https://www.flowdock.com/app/rulemotion/r-resinos/threads/I2dKbE6sFRPfs1cOUakZP4d2Zzg) it sounds as if this should not be the case.

Tested by connecting pins 8/10 (TXD0/RXD0) from relevant boards to a USB Serial cable and running minicom at 115200/8N1/no flow control.

**Comment by agherzan** [comment]
The current shipped images of resinOS all are development images. These enable serial console on Raspberry pi.

**Comment by hedss** [comment]
OK, it's a non-issue then. Ta.
