### ISSUE TITLE
Docker pull from private repos

### ISSUE THREAD

**Issue by nite** [resin-os/resinos#157]
Hi, 

I can't docker login via an ssh session directly onto resin, or a proxied session locally. 

`DOCKER_API_VERSION=1.22 DOCKER_HOST=tcp://<resin.local ip address>:2375 docker login
ssh root@resin.local -p22222`

The latter returns this due to the read-only-filesystem. 

`Error saving config file: mkdir /home/root/.docker: read-only file system`

Any suggestions? The architecture docs seem to indicate `/home` shouldn't be read-only? 

(I've mentioned this on the resin-os gitter chat)

**Comment by agherzan** [comment]
Hello @nite . Indeed the entire root filesystem is read only. We only allow some specific locations on the disk to be rw by bind mounting them to another persistent partition. In the case of the home directory we only bind mount a specific file for openssl support (https://github.com/resin-os/meta-resin/blob/master/meta-resin-common/recipes-support/resin-mounts/resin-mounts/home-root-.rnd.mount) . So, that .docker location is not rw.

 We will take a look on this and come back as soon as we have something.

**Comment by petrosagg** [comment]
It looks like we have to add `~/.docker` in the list of writable directories

**Comment by agherzan** [comment]
I agree @petrosagg .

**Comment by agherzan** [comment]
PR merged. This will be available in the next 2.X release.

**Comment by agherzan** [comment]
For ref.: https://github.com/docker/docker/pull/20565
