### ISSUE TITLE
.dockerignore not working

### ISSUE THREAD

**Issue by nite** [resin-os/resinos#158]
Hi, 

I have a folder with a `node_modules` folder in it, locally a `docker build `works fine as `node_modules` is in my `.dockerignore` file, however a `rdt push resin.local -s .` times out unless I move only the files for the docker build into a separate folder (without `node_modules`) & build from there - I can only assume that this means that `rdt push` is ignoring my `.dockerfile` - any ideas or suggestions?

**Comment by lekkas** [comment]
Hey @nite ,

`rdt` will normally:

a. parse and ignore any files included in `.gitignore`
b. ignore `.git` and `node_modules/`

Do you get any build process output that you can paste here after `rdt push resin.local -s .` ? Also, can you try added the `--verbose` flag ?

**Comment by nite** [comment]
No output, but I'll have to wait til I'm of holidays for that verbose flag!
I'll see if I can sneak it in on some downtime

**Comment by nite** [comment]
This seems to be a non-issue now, I'll reopen if it comes back.
