### ISSUE TITLE
xt_set kernel module missing from HOST OS VERSION Resin OS 1.24.0

### ISSUE THREAD

**Issue by ab77** [resin-os/resinos#169]
Resin OS 1.24.0

xt_set.ko kernel module missing from x86_64 ResinOS, however it is present in armv7l.

```
--- present in armv7l (RPi2/3):
# find / -name ip_set.*
/lib/modules/4.1.21/kernel/net/netfilter/ipset/ip_set.ko.gz
/usr/include/linux/netfilter/ipset/ip_set.h

# find / -name xt_set.*
/lib/modules/4.1.21/kernel/net/netfilter/xt_set.ko.gz
/usr/include/linux/netfilter/xt_set.h


--- missing in x86_86 (iNUC):
# find / -name ip_set.*
/lib/modules/4.1.8-yocto-standard/kernel/net/netfilter/ipset/ip_set.ko
/usr/include/linux/netfilter/ipset/ip_set.h

# find / -name xt_set.*
/usr/include/linux/netfilter/xt_set.h
```

Could you please compile the missing module in the next release of the OS.

It would also be good to cross reference kernel modules in other ResinOS architectures (i.e. RPi) with x86 and get parity between both, architectural differences permitting.

Cheers!

-- ab1

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_10yl)

**Comment by agherzan** [comment]
- [ ] Available in master branch
- [ ] Available in 1.X branch
- [ ] Tests merged

**Comment by ab77** [comment]
Any update on wrangling this module into the x86 OS?
