### ISSUE TITLE
Create jenkins jobs to build all variants of resinOS simultaneously

### ISSUE THREAD

**Issue by shaunmulligan** [resin-os/resinos#170]
Currently, we have 2 issues with the build and release pipeline:
1) we don't release new unmanaged ResinOS 2.0-beta image whenever we release them on the resin.io platform.
2.) We do not have the flexibility to easily deploy 1.X and 2.X for a specific device type.

Both of these issues are becoming more and more important as we approach resinOS 2.0 release. In a perfect world we should have control to deploy any of the following variants to any of our supported boards easily:

* unmanaged resinOS (development)
* unmanaged resinOS (production) // This version will have to come later once the prod workflow is worked out.
* managed resinOS (development)
* manage resinOS (production) - 2.0
* manage resinOS (production) - 1.X

**Comment by agherzan** [comment]
To be picked after https://github.com/resin-os/resinos/issues/182 is done.

**Comment by agherzan** [comment]
This was implemented for all the deployed boards to 2.0.0.
