### ISSUE TITLE
Make sure builds add the `-dev` or `-prod` variant to `/etc/os-release`

### ISSUE THREAD

**Issue by shaunmulligan** [resin-os/resinos#173]
`/etc/os-release` should indicate the `-dev` variant [see link](https://www.freedesktop.org/software/systemd/man/os-release.html#VARIANT=). for development builds and production builds should show  `-prod`.

**Comment by agherzan** [comment]
Sounds good. Just to clarify:
```

Development:
VARIANT = "Development"
VARIANT_ID = "dev"

Production
VARIANT = "Production"
VARIANT_ID = "prod"
```

Sounds good?
