### ISSUE TITLE
Test 2.X on all supported device types

### ISSUE THREAD

**Issue by shaunmulligan** [resin-os/resinos#176]
- [x] Beaglebone (all)
- [x] RaspberryPi (all)
- [x] Artik5
- [x] Artik710
- [x] Kitra710
- [x] NUC
- [x] TS4900
- [x] Upboard

**Comment by shaunmulligan** [comment]
artik 10 fails: #167 
artik 5 fails: #175 
intel edison fails: #168

**Comment by agherzan** [comment]
@shaunmulligan Can we close this as we already moved to another release?

**Comment by shaunmulligan** [comment]
@agherzan can we rather rename the ticket. We haven't tested 2.0 on some of the boards yet

**Comment by agherzan** [comment]
Fair.

**Comment by shaunmulligan** [comment]
@agherzan I think this can be closed now

**Comment by agherzan** [comment]
@shaunmulligan there are 2 exceptions as you know (Artik5 and bbb Green). But we plan to unify beaglebone and drop Artik5, right?

**Comment by shaunmulligan** [comment]
@agherzan we aren't dropping the Artik5

**Comment by agherzan** [comment]
That was my understanding which makes this issue still in progress as the artik5 was not released to 2.0.

**Comment by floion** [comment]
All supported boards are known to work on 2.X
Closing this item
