### ISSUE TITLE
Investigate mender and swupdate alternatives to resinhup

### ISSUE THREAD

**Issue by agherzan** [resin-os/resinos#178]

**Comment by linux4kix** [comment]
I have been testing mender.io as part of resin.io.  So far everything seems to work quite well together.  I am still working on documentation for it.  I have had some conversations with the Mender.io team and they are more than willing to help if more work is needed.

**Comment by alexandrosm** [comment]
Hi @linux4kix, it's best to discuss with @petrosagg for this. So far mender
has not been considered appropriate for what we want to do, perhaps a
conversation can get everyone on the same page?

-- 

*Alexandros Marinos*

Founder & CEO, Resin.io


+1 206-637-5498

@alexandrosm

**Comment by chriswiggins** [comment]
Sorry to drag up an old thread - I see ResinOS by default has two partitions as well and integrates well with your cloud for updates. I'm looking at using Mender for an on-premise installation so is there any way of doing this?

**Comment by chriswiggins** [comment]
Fair enough! We're interested in Resin anyway so I'm looking forward to hearing back from Phillip. Cheers

**Comment by agherzan** [comment]
Sounds good!
