### ISSUE TITLE
Racing issue while building am57xx images

### ISSUE THREAD

**Issue by agherzan** [resin-os/resinos#184]
Branch: master (resin-am571x-evm)

Seems like resinhup images can't be generated due to the fact that rootfs tar is not generated.

`| tar: /yocto/resin-board/build/tmp/deploy/images/am57xx-evm/resin-image-am57xx-evm-20170129212730.rootfs.tar: Cannot open: No such file or directory | tar: Error is not recoverable: exiting now | WARNING: exit code 2 from a shell command. | ERROR: Function failed: do_image_resinhup_tar (log file is located at /yocto/resin-board/build/tmp/work/am57xx_evm-poky-linux-gnueabi/resin-image/1.0-r0/temp/log.do_image_resinhup_tar.11044) NOTE: recipe resin-image-1.0-r0: task do_image_resinhup_tar: Failed ERROR: Task (/yocto/resin-board/build/../layers/meta-resin/meta-resin-common/recipes-core/images/resin-image.bb:do_image_resinhup_tar) failed with exit code '1' `

**Comment by floion** [comment]
fixed by https://github.com/resin-os/meta-resin/pull/566
