### ISSUE TITLE
Cannot download application on a beaglebone green wireless

### ISSUE THREAD

**Issue by floion** [resin-os/resinos#193]
"Failed to download application 'registry.resinstaging.io/ ... " due to 'Error pulling image (latest) from registry.resinstaging.io/ ..., failed to register layer: ApplyLayer exit status 1 stdout: stderr: unexpected EOF'

This message appears multiple times as it retries to download the new user container.
This has been observed also on a user rpi3 board.

The download eventually goes through (in my case after 30 minutes of retrying) but we should do something at least message wise I think

**Comment by agherzan** [comment]
@floion As far as i know you could not reproduce this issue anymore, right?

**Comment by agherzan** [comment]
@imrehg can you confirm you testes this on the latest release and provisioned fine on a Green WiFi? (using the beaglebone device type)

**Comment by imrehg** [comment]
Resinos `v2.0.0+rev4` using "BeagleBone Black" device type and a BBGW device, successfully provisioned and downloaded the application.
