### ISSUE TITLE
[Proposal] rename resin-conf --> resin-state

### ISSUE THREAD

**Issue by shaunmulligan** [resin-os/resinos#207]
It was suggested during an arch call that we should rename the current `resin-conf` partition to `resin-state` since its more accurate.

I am not sure of the global affect of this, but I think both the CLI and Image maker will need to be aware of the change.

**Comment by agherzan** [comment]
I agree with this. As well I would add change of resin-root/resin-updt to resin-rootA/resin-rootB . I don't know the impact on other components either.

**Comment by shaunmulligan** [comment]
@agherzan this issue is already closed right?

**Comment by agherzan** [comment]
Addressed as part of https://github.com/resin-os/meta-resin/pull/577 .
