### ISSUE TITLE
Modify resin-supervisor services to ensure symlinks get created in the root-overlay

### ISSUE THREAD

**Issue by josephroberts** [resin-os/resinos#208]
Currently systemd writes a symlink to `/etc/systemd/system` which is a RO file system when enabling these services:
* `/lib/systemd/system/resin-supervisor.service`
* `/lib/systemd/system/update-resin-supervisor.service`
* `/lib/systemd/system/update-resin-supervisor.timer`

To prevent this the services need to have `WantedBy=resin.target` at the end which will mean the symlinks get created in the RW root-overlay instead.

This is part of the [RDT promote spec](https://github.com/resin-io/hq/pull/451)

@pcarranzav @agherzan can you confirm this sounds sane?

**Comment by agherzan** [comment]
@josephroberts I have one concern about this. The reset mechanism (resin-state-reset) will reset these symlinks when trigger. This will get fixed after a host os update though. @petrosagg what do you think?

**Comment by josephroberts** [comment]
@agherzan I have manually made these changes to my image and I have not noticed any issues. Is it a case of updating the behavior of the reset mechanism to avoid resetting the symlinks when its triggered?

**Comment by agherzan** [comment]
In the current design. They will need to make sure they resinhup before resetting the state partition (if at all).

**Comment by agherzan** [comment]
@josephroberts please talk to @petrosagg about this.

**Comment by agherzan** [comment]
Discussed with @petrosagg and we agreed that my raised issue is not a problem. resinos devices promoted to resinio should get back to the resinos non promoted state when the state partition is reset.

**Comment by alexandrosm** [comment]
Will this be the case for "regular" resin.io devices too?

-- 

*Alexandros Marinos*

Founder & CEO, Resin.io


+1 206-637-5498

@alexandrosm

**Comment by agherzan** [comment]
@alexandrosm no. After you promote and resinhup to a resinio image, resetting the state partition will keep the device promoted (because it was resinhuped to a resinio image so reseting it will keep a resinio image).

**Comment by alexandrosm** [comment]
what does it mean for a device to be promoted? where is that information
stored? can you give me a specific example or examples of that kind of
information? (this can wait until after EW)

-- 

*Alexandros Marinos*

Founder & CEO, Resin.io


+1 206-637-5498

@alexandrosm

**Comment by agherzan** [comment]
Hi @alexandrosm . Device promoted are the ones that were provisioned as resin unmanaged devices and then, through the provisioner promoted to managed. This process creates a bunch of symlinks in the state partition and pulls in the supervisor image. If after this process a user resets the state partition, these symlinks are removed and the devices get's in an unmanaged stated again. In order to avoid this, I user needs to upgrade to a managed resinOS which will make the symlinks persistent in the root file-system.
