### ISSUE TITLE
Include the `resin-provisioner` binary in resinOS

### ISSUE THREAD

**Issue by josephroberts** [resin-os/resinos#209]
As part of the [RDT spec](https://github.com/resin-io/hq/pull/451) we need the `resin-provisioner` binary to be included in resinOS. This binary should be built for each architecture as part of the resinOS build process. The binary must be stored in a location that allows for it to be called from the host and from the user container.

The build commands would be something like:
```
git clone https://github.com/resin-os/resin-provisioner.git
cd resin-provisioner
env GOOS=linux GOARCH=arm go build ./cmd/resin-provision
```

replace `GOARCH` with the target architecture

**Comment by agherzan** [comment]
The provisioner is already compiled and included in our connectable images (which is both the resinOS managed and unmanaged). 

Ref:
https://github.com/resin-os/meta-resin/blob/master/meta-resin-common/recipes-core/packagegroups/packagegroup-resin.bb#L26
https://github.com/resin-os/meta-resin/blob/master/meta-resin-common/recipes-go/resin-provisioner/resin-provisioner_1.0.4.bb

**Comment by josephroberts** [comment]
@agherzan cool. Where does it live currently? Is it available from the user container? How does it get updated - do you pull master everytime a new image is released?

**Comment by shaunmulligan** [comment]
@agherzan I looked around on a production device and a resinOS unmanaged build and neither of them seems to have it anywhere in the rootFS

**Comment by agherzan** [comment]
I'll take a look and come back.

**Comment by agherzan** [comment]
@shaunmulligan What version did you test it on? I just tried on the latest version and I get resin-provision binary deployed as expected on a nuc machine.

**Comment by shaunmulligan** [comment]
@agherzan I think I tested on resinOS unmanaged beta.1 or the beta10rev1, but can't remember. Where is the binary put in the FS?

**Comment by agherzan** [comment]
`/use/bin/resin-provision`

**Comment by josephroberts** [comment]
@agherzan  found it, but its not available from the user container - it needs to be.

I have couple of questions:
Would the master of `resin-provision` get built for each new image release?
What happens if we need to update `resin-provision` - would this require a whole new image release?

**Comment by agherzan** [comment]
@josephroberts this tool is part of the OS so it will come with new image releases.
About the path I can't say too much. Maybe @petrosagg can give us an idea.

**Comment by shaunmulligan** [comment]
@josephroberts , why does it need to be accessible from any container? The user needs to be able to run a container with the path to the binary mounted in I would guess

**Comment by josephroberts** [comment]
@shaunmulligan "The user needs to be able to run a container with the path to the binary mounted in I would guess" - how would they do this?

**Comment by shaunmulligan** [comment]
They need a way to control how containers are started in their system, like we have with the supervisor

**Comment by shaunmulligan** [comment]
Or they need a tunnel into the host so they can use the docker binary directly rather than using the socket like our supervisor does

**Comment by agherzan** [comment]
We can close this as resin-provisioner is included in the host OS (https://github.com/resin-os/meta-resin/blob/master/meta-resin-common/recipes-go/resin-provisioner/resin-provisioner_1.0.4.bb). Even so, this will be completely re-implemented as part of the Managed/Unmanaged unification activity.
