### ISSUE TITLE
Determine if we need a redundant boot parition for RPi family of devices.

### ISSUE THREAD

**Issue by shaunmulligan** [resin-os/resinos#210]
We need to determine how much of a risk it is to have only one boot partition. If its found that this can make resinOS devices fail during resinHUP, we may need to include a second partition.

**Comment by lurch** [comment]
IIRC it's not actually possible to have a secondary boot partition on RPi devices? They just always boot from the first FAT-format partition on the SD card.

**Comment by lurch** [comment]
(unless you want to make use of the system that NOOBS uses, where the "first stage" boot partition has the ability to "reboot" the RPi and get it to load from a different boot partition by setting specific bits - so in this case we'd actually need 3 boot partitions)

**Comment by shaunmulligan** [comment]
@lurch yeah I believe the plan is to have a first stage boot loader and then uboot as the second stage with the two boot partitions

**Comment by agherzan** [comment]
@shaunmulligan can we close this ticket?

**Comment by shaunmulligan** [comment]
Yup we can

**Comment by bbinet** [comment]
I'm interested in this issue, and wondered what has been decided on this redundant boot partition. And what is the current state state of this feature: has it already been implemented in resinos 2.0?
