### ISSUE TITLE
Add support for wifi channels 12/13 for the raspberrypi3

### ISSUE THREAD

**Issue by Page-** [resin-os/resinos#212]
<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_14nv)

**Comment by willnewton** [comment]
This is likely a problem for more than raspberry pi as all wifi devices should know their regulatory domain. It's possible to set regulatory domain with 802.11d automatically but my understanding is the FCC have recently disallowed this so device SKUs for shipment to the US have to have the high channels disabled in firmware. So it may be that we need to have an option when configuring an image to set the regulatory domain (this could be as simple as US vs rest of the world with 802.11d).

**Comment by lurch** [comment]
This is something I know absolutely nothing about, but it's a problem that was recently solved in [NOOBS](https://github.com/raspberrypi/noobs), in case that provides any helpful pointers.
https://github.com/raspberrypi/noobs/issues/386
https://github.com/raspberrypi/noobs/commit/5136f34c9aa0a2550b89eb17bc07aaad1d1fbf3b

**Comment by floion** [comment]
Done by https://github.com/resin-os/meta-resin/pull/681
