### ISSUE TITLE
Root-overlay bind mount service not running

### ISSUE THREAD

**Issue by josephroberts** [resin-os/resinos#213]
The `etc-systemd-system-resin.target.wants.mount` service is not running on boot which means you cannot enable any services without making the FS RW.

Freshly burned image, first boot:
```
root@resin:~# systemctl status etc-systemd-system-resin.target.wants.mount  
● etc-systemd-system-resin.target.wants.mount - Resin target mount point to persistent location
   Loaded: loaded (/lib/systemd/system/etc-systemd-system-resin.target.wants.mount; enabled; vendor preset: enabled)
   Active: inactive (dead)
    Where: /etc/systemd/system/resin.target.wants
     What: /mnt/conf/root-overlay/etc/systemd/system/resin.target.wants
root@resin:~# touch /etc/systemd/system/resin.target.wants/test.txt
touch: cannot touch '/etc/systemd/system/resin.target.wants/test.txt': Read-only file system
root@resin:~# systemctl start etc-systemd-system-resin.target.wants.mount  
root@resin:~# touch /etc/systemd/system/resin.target.wants/test.txt       
root@resin:~# ls /etc/systemd/system/resin.target.wants/
test.txt
root@resin:~# 
```

[Flowdock](https://www.flowdock.com/app/rulemotion/r-resinos/threads/xlumgGZYP4Ol4qqCwGgWdOJf4Ex)

**Comment by agherzan** [comment]
This is because the resin-supervisor service has the dependency on etc-systemd-system-resin.target.wants.mount . I think it would be reasonable to move this dependecy as a docker's one which would fix this problem on unmanaged as well. @floion @telphan @michal-mazurek Any comments about it?

**Comment by floion** [comment]
That would not be a natural dependency. And it would not make sense later when inspecting the docker service later.
Instead, can we not have the provisioner do this? If it is part of the promotion process, then I guess this promotion process would be responsible of enabling this service in the initial steps of the process.
Is that feasible @josephroberts ?

**Comment by josephroberts** [comment]
@floion @agherzan yes I can enable the service before starting the promotion if that's the best approach.

**Comment by agherzan** [comment]
I totally agree with @floion on this. I was more trying to find a compromise but having it in the provision sounds like the way forward.
