### ISSUE TITLE
resinOS website title

### ISSUE THREAD

**Issue by imrehg** [resin-os/resinos#216]
The template for the resinOS website capitalizes the `repo.name` in the `<title>`, header, resulting in `Resinos`, while the OpenGraph title is not capitalized so shown as `resinOS`. 
https://github.com/resin-os/resinos/blob/46e9ab919b9cbd716e8c8ae4a68c3ba6755cea23/templates/default.html#L6-L7

I'm guessing it would be better to show the title as used, that is `resinOS`?

**Comment by craig-mulligan** [comment]
Yea sounds fine to me.
