### ISSUE TITLE
Container dns doesn't work with non-default docker bridge subnet

### ISSUE THREAD

**Issue by petrosagg** [resin-os/resinos#229]
Currently when we start docker we have a hardcoded `--dns` parameter set to `172.17.0.1` and also the systemd services adds iptables rules to forward DNS traffic going to `172.17.0.1` to `127.0.0.2`, which is our local dnsmasq resolver.

This is wrong because when the docker daemon starts up it tries to find a free subnet to create its `docker0` bridge in. It can happen that the `172.17.0.1/16` subnet is already taken (by wifi for example) and so docker0 will be in one of the other private subnets in IPv4. When this happens the containers will try to resolve using a non-existent DNS server.

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_25b7)

**Comment by shaunmulligan** [comment]
@petrosagg do you have a good idea of how we will fix this? or should we bring it to an arch call?

**Comment by petrosagg** [comment]
@shaunmulligan no I don't, and I don't think this is a topic for an arch call. It needs investigation on a device.

**Comment by shaunmulligan** [comment]
@petrosagg could we perhaps use something like the `--dns` option when starting containers? I guess this would be pretty hacky though

**Comment by petrosagg** [comment]
I don't understand the proposed solution. Can you give more details?

**Comment by shaunmulligan** [comment]
after re-reading the docs, I don't actually think its a solution :P  This bug suck, because it happens on both the organge pi and the nanopi always. I don't know why the 172.17.x.x subnet is never taken by the docker bridge. Maybe something new introduced in kernel (both devices run 4.11.5)

**Comment by shaunmulligan** [comment]
@agherzan @petrosagg  I noticed in my kernel 4.11 boot logs of the Nanopi, the following log:
```
[    0.697806] bridge: filtering via arp/ip/ip6tables is no longer available by default. Update your scripts to load br_netfilter if you need this.
``` 
could this be cause for why docker consistently doesn't attach the bridge on 172.17.0.1

**Comment by floion** [comment]
@shaunmulligan I get this on a device which did not get a kernel update iirc.
The only thing that changed was meta-resin

**Comment by floion** [comment]
Guess this can be closed now that https://github.com/resin-os/meta-resin/pull/802 is merged?

**Comment by petrosagg** [comment]
Yes, closing
