### ISSUE TITLE
Support Kitra 520

### ISSUE THREAD

**Issue by agherzan** [resin-os/resinos#237]

**Comment by floion** [comment]
@agherzan is this supposed to be kitra520 instead of kitra530?

**Comment by agherzan** [comment]
@floion I don't think so. @curcuz probably knows more.

**Comment by floion** [comment]
Who opened this issue?

**Comment by agherzan** [comment]
As you can see above, I did. As far as I remember though this was based on a discussion with Carlo. But if I review this in the PRs I think it was actually 520 - recall the kernel patch. I'll let @curcuz confirm and we can close it if so.

**Comment by curcuz** [comment]
@agherzan that discussion was on kitra520

**Comment by agherzan** [comment]
Renamed accordingly and closed as this is currently supported by https://github.com/resin-os/resin-artik
