### ISSUE TITLE
The Intel edison's boot partition size is not 40 MB

### ISSUE THREAD

**Issue by floion** [resin-os/resinos#238]
Observed on both 1.X and 2.X, the boot partition (mmcblk0p7 in edison's case) is not 40 MB.

On 1.X (1.26-rc0):

root@edison:~# fdisk -l /dev/mmcblk0p7
Disk /dev/mmcblk0p7: 40 MiB, 41943040 bytes, 81920 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: dos
Disk identifier: 0x00000000

and

root@edison:~# df -h /mnt/boot/
Filesystem Size Used Avail Use% Mounted on
/dev/mmcblk0p7 6.1M 5.6M 574K 91% /mnt/boot

On 2.X:

root@resin:~# fdisk -l /dev/mmcblk0p7
Disk /dev/mmcblk0p7: 40 MiB, 41943040 bytes, 81920 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: dos
Disk identifier: 0x00000000

But:

root@resin:~# df -h /mnt/boot/
Filesystem Size Used Avail Use% Mounted on
/dev/mmcblk0p7 9.1M 8.5M 628K 94% /mnt/boot

**Comment by agherzan** [comment]
This is not a priority for 2.0 so I'll get it out of the milestone.

**Comment by michal-mazurek** [comment]
connect https://github.com/resin-os/resin-edison/pull/72
