### ISSUE TITLE
File package was rebased making yocto builds fail

### ISSUE THREAD

**Issue by agherzan** [resin-os/resinos#241]

**Comment by michal-mazurek** [comment]
This looks like it took care of itself ten hours ago:
`commit e292e935b077a95ae093d4b425c7e95b177b030b
Author: Richard Purdie <richard.purdie@linuxfoundation.org>
Date:   Tue Mar 21 22:17:57 2017 +0000

    Revert "file: update SRCREV for 5.28 to fix fetch fail on missing commit"
    
    This reverts commit 87c17b352daa63bc4f62e8802982288ab1839f1b.
    
    Upstream restored the original hashes.
    
    Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>`
