### ISSUE TITLE
Make sure RPI zero and zero W are clocked at the full 1GHz

### ISSUE THREAD

**Issue by shaunmulligan** [resin-os/resinos#245]
In our current firmware, the RPI zero CPU is capped at 700MHz, apparently this has been fixed by the RPI foundation in this https://github.com/raspberrypi/firmware/commit/f5446ba0b3bbd4241bf0ad35a2c9f299f5c447d5

We should make sure we get this latest firmware to ensure our devices run at the correct clock speed.

**Comment by lurch** [comment]
I believe the RPI Zero CPU is already running at 1GHz, it was only the RPi Zero W that was running at the old 700MHz, because the firmware forgot to account for the new revision code used by the Zero W.

**Comment by shaunmulligan** [comment]
@lurch yeah, that is what I thought as well, but it seems like all RPI zeros on resin run at 700MHz, i have one running here and if I do `watch -n 1 cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_cur_freq ` it never goes above 700, no matter what other processes I run. On this RPI zero i have mopidy streaming music and I did an `apt-get update` but no change over 700MHz... Maybe my testing method is wrong, any suggestions?

**Comment by lurch** [comment]
Ah, I haven't actually tested on resinos, I was referring to Raspbian.

**Comment by shaunmulligan** [comment]
its weird, it should be the same as raspbian since its the firmware, but maybe we have very old firmware

**Comment by agherzan** [comment]
This was due to the default governor: https://github.com/resin-os/meta-resin/pull/654 . Merged in master meta-resin.
