### ISSUE TITLE
Add support for Beaglebone Blue to resinOS

### ISSUE THREAD

**Issue by willnewton** [resin-os/resinos#255]
Get resinOS booting and wireless working on the Beaglebone Blue board.

**Comment by agherzan** [comment]
@willnewton can you link the PR and close this issue? I think it is done. BTW, the current implementation just uses the same image as bbb, right?

**Comment by willnewton** [comment]
Added here: https://github.com/resin-os/resin-beaglebone/pull/79

The current implementation is to use machine "beaglebone" for BeagleBone Blue (as well as Black and in theory other types).

**Comment by agherzan** [comment]
CC @shaunmulligan

**Comment by shaunmulligan** [comment]
This is cool! so eventually over time we could look at removing the other Beaglebone device types right?

**Comment by agherzan** [comment]
That's the plan - as soon as we can handle the old device types.
