### ISSUE TITLE
wlcore kernel module fails and wifi does not work on beaglebone green wifi

### ISSUE THREAD

**Issue by floion** [resin-os/resinos#259]
The wlcore/wl18xx kernel module fails on the beaglebone green wifi on version 2.0.0-rc5.rev1

If we revert a kernel patch, like in this PR https://github.com/resin-os/resin-beaglebone/pull/82 , then the wifi kernel module does not crash anymore.
However, even after this the wifi is not functioning correctly. Symptoms for this other problem have been described here: https://mail.gnome.org/archives/networkmanager-list/2017-March/msg00094.html

**Comment by willnewton** [comment]
I have merged the BeagleBone Blue changes to master which includes a kernel bump and drops the problematic kernel change in the linked issue.

I have tested the wifi on the Blue and it seems to be working ok:

    Mar 27 10:44:43 beaglebone systemd[1]: Starting Network Manager...
    Mar 27 10:44:44 beaglebone NetworkManager[905]: <info>  [1490611484.2917] NetworkManager (version 1.4.2) is starting...
    Mar 27 10:44:44 beaglebone NetworkManager[905]: <info>  [1490611484.3084] Read config: /etc/NetworkManager/NetworkManager.conf
    Mar 27 10:44:44 resin NetworkManager[905]: <info>  [1490611484.6539] manager[0xfa9028]: monitoring kernel firmware directory '/lib/firmware'.
    Mar 27 10:44:45 resin NetworkManager[905]: <info>  [1490611485.0774] dns-mgr[0xfb9018]: init: dns=default, rc-manager=resolvconf
    Mar 27 10:44:45 resin NetworkManager[905]: <info>  [1490611485.0871] rfkill0: found WiFi radio killswitch (at /sys/devices/platform/ocp/47810000.mmc/mmc_host/mmc2/mmc2:0001/mmc2:0001:2/wl18xx.2.auto/ieee80211/phy0/rfkill0) (driver wl18xx_driver)
    Mar 27 10:44:45 resin NetworkManager[905]: <info>  [1490611485.0908] manager[0xfa9028]: WiFi hardware radio set enabled
    Mar 27 10:44:45 resin NetworkManager[905]: <info>  [1490611485.0931] manager[0xfa9028]: WWAN hardware radio set enabled
    Mar 27 10:44:45 resin systemd[1]: Started Network Manager.
    Mar 27 10:44:45 resin NetworkManager[905]: <info>  [1490611485.8107] settings: loaded plugin keyfile: (c) 2007 - 2015 Red Hat, Inc.  To report bugs please use the NetworkManager mailing list.
    Mar 27 10:44:46 resin NetworkManager[905]: <info>  [1490611486.3185] keyfile: new connection /etc/NetworkManager/system-connections/resin-sample (bcb05b81-52cb-3828-8088-c0f55e950375,"resin-sample")
    Mar 27 10:44:46 resin NetworkManager[905]: <info>  [1490611486.8808] settings: hostname: using hostnamed
    Mar 27 10:44:46 resin NetworkManager[905]: <info>  [1490611486.8834] settings: hostname changed from (none) to "resin"
    Mar 27 10:44:46 resin NetworkManager[905]: <info>  [1490611486.8946] dhcp-init: Using DHCP client 'dhclient'
    Mar 27 10:44:46 resin NetworkManager[905]: <info>  [1490611486.9084] manager: WiFi enabled by radio killswitch; enabled by state file
    Mar 27 10:44:46 resin NetworkManager[905]: <info>  [1490611486.9089] manager: WWAN enabled by radio killswitch; enabled by state file
    Mar 27 10:44:46 resin NetworkManager[905]: <info>  [1490611486.9091] manager: Networking is enabled by state file
    Mar 27 10:44:46 resin NetworkManager[905]: <info>  [1490611486.9096] Loaded device plugin: NMVxlanFactory (internal)
    Mar 27 10:44:46 resin NetworkManager[905]: <info>  [1490611486.9098] Loaded device plugin: NMVlanFactory (internal)
    Mar 27 10:44:46 resin NetworkManager[905]: <info>  [1490611486.9100] Loaded device plugin: NMVethFactory (internal)
    Mar 27 10:44:46 resin NetworkManager[905]: <info>  [1490611486.9102] Loaded device plugin: NMTunFactory (internal)
    Mar 27 10:44:46 resin NetworkManager[905]: <info>  [1490611486.9104] Loaded device plugin: NMMacvlanFactory (internal)
    Mar 27 10:44:46 resin NetworkManager[905]: <info>  [1490611486.9106] Loaded device plugin: NMIPTunnelFactory (internal)
    Mar 27 10:44:46 resin NetworkManager[905]: <info>  [1490611486.9107] Loaded device plugin: NMInfinibandFactory (internal)
    Mar 27 10:44:46 resin NetworkManager[905]: <info>  [1490611486.9109] Loaded device plugin: NMEthernetFactory (internal)
    Mar 27 10:44:46 resin NetworkManager[905]: <info>  [1490611486.9112] Loaded device plugin: NMBridgeFactory (internal)
    Mar 27 10:44:46 resin NetworkManager[905]: <info>  [1490611486.9114] Loaded device plugin: NMBondFactory (internal)
    Mar 27 10:44:46 resin NetworkManager[905]: <info>  [1490611486.9422] Loaded device plugin: NMWifiFactory (/usr/lib/NetworkManager/libnm-device-plugin-wifi.so)
    Mar 27 10:44:47 resin NetworkManager[905]: <info>  [1490611487.0031] Loaded device plugin: NMWwanFactory (/usr/lib/NetworkManager/libnm-device-plugin-wwan.so)
    Mar 27 10:44:47 resin NetworkManager[905]: <info>  [1490611487.0277] Loaded device plugin: NMBluezManager (/usr/lib/NetworkManager/libnm-device-plugin-bluetooth.so)
    Mar 27 10:44:47 resin NetworkManager[905]: <info>  [1490611487.0470] device (lo): link connected
    Mar 27 10:44:47 resin NetworkManager[905]: <info>  [1490611487.0671] manager: (lo): new Generic device (/org/freedesktop/NetworkManager/Devices/0)
    Mar 27 10:44:47 resin NetworkManager[905]: <info>  [1490611487.0983] manager: (can0): new Generic device (/org/freedesktop/NetworkManager/Devices/1)
    Mar 27 10:44:47 resin NetworkManager[905]: <info>  [1490611487.1089] (wlan0): using nl80211 for WiFi device control
    Mar 27 10:44:47 resin NetworkManager[905]: <info>  [1490611487.1142] device (wlan0): driver supports Access Point (AP) mode
    Mar 27 10:44:47 resin NetworkManager[905]: <info>  [1490611487.1427] manager: (wlan0): new 802.11 WiFi device (/org/freedesktop/NetworkManager/Devices/2)
    Mar 27 10:44:47 resin NetworkManager[905]: <info>  [1490611487.1805] device (wlan0): state change: unmanaged -> unavailable (reason 'managed') [10 20 2]
    Mar 27 10:44:47 resin NetworkManager[905]: <info>  [1490611487.8455] device (wlan0): set-hw-addr: set MAC address to 1E:A6:04:AB:CE:42 (scanning)
    Mar 27 10:44:48 resin NetworkManager[905]: <info>  [1490611488.7392] ModemManager available in the bus
    Mar 27 10:44:48 resin NetworkManager[905]: <info>  [1490611488.8467] supplicant: wpa_supplicant running
    Mar 27 10:44:48 resin NetworkManager[905]: <info>  [1490611488.8490] device (wlan0): supplicant interface state: init -> starting
    Mar 27 10:44:48 resin NetworkManager[905]: <info>  [1490611488.9417] sup-iface[0xfb7208,wlan0]: supports 1 scan SSIDs
    Mar 27 10:44:48 resin NetworkManager[905]: <info>  [1490611488.9717] device (wlan0): supplicant interface state: starting -> ready
    Mar 27 10:44:48 resin NetworkManager[905]: <info>  [1490611488.9743] manager: startup complete
    Mar 27 10:44:48 resin NetworkManager[905]: <info>  [1490611488.9837] device (wlan0): state change: unavailable -> disconnected (reason 'supplicant-available') [20 30 42]
    Mar 27 10:44:50 resin NetworkManager[905]: <info>  [1490611490.1738] manager: (docker0): new Bridge device (/org/freedesktop/NetworkManager/Devices/3)
    Mar 27 10:44:53 resin NetworkManager[905]: <info>  [1490611493.0611] device (wlan0): supplicant interface state: ready -> inactive
    Mar 27 10:44:53 resin NetworkManager[905]: <info>  [1490611493.1459] policy: auto-activating connection 'resin-sample'
    Mar 27 10:44:53 resin NetworkManager[905]: <info>  [1490611493.1780] device (wlan0): Activation: starting connection 'resin-sample' (bcb05b81-52cb-3828-8088-c0f55e950375)
    Mar 27 10:44:53 resin NetworkManager[905]: <info>  [1490611493.1859] device (wlan0): state change: disconnected -> prepare (reason 'none') [30 40 0]
    Mar 27 10:44:53 resin NetworkManager[905]: <info>  [1490611493.1983] manager: NetworkManager state is now CONNECTING
    Mar 27 10:44:53 resin NetworkManager[905]: <info>  [1490611493.2617] device (wlan0): set-hw-addr: set-cloned MAC address to DE:AD:BE:EF:00:00 (permanent)
    Mar 27 10:44:53 resin NetworkManager[905]: <info>  [1490611493.8515] device (wlan0): supplicant interface state: inactive -> disabled
    Mar 27 10:44:53 resin NetworkManager[905]: <info>  [1490611493.8690] device (wlan0): supplicant interface state: disabled -> inactive
    Mar 27 10:44:53 resin NetworkManager[905]: <info>  [1490611493.8770] device (wlan0): state change: prepare -> config (reason 'none') [40 50 0]
    Mar 27 10:44:53 resin NetworkManager[905]: <info>  [1490611493.8858] device (wlan0): Activation: (wifi) access point 'resin-sample' has security, but secrets are required.
    Mar 27 10:44:53 resin NetworkManager[905]: <info>  [1490611493.8877] device (wlan0): state change: config -> need-auth (reason 'none') [50 60 0]
    Mar 27 10:44:54 resin NetworkManager[905]: <info>  [1490611494.0124] device (wlan0): state change: need-auth -> prepare (reason 'none') [60 40 0]
    Mar 27 10:44:54 resin NetworkManager[905]: <info>  [1490611494.0289] device (wlan0): state change: prepare -> config (reason 'none') [40 50 0]
    Mar 27 10:44:54 resin NetworkManager[905]: <info>  [1490611494.0388] device (wlan0): Activation: (wifi) connection 'resin-sample' has security, and secrets exist.  No new secrets needed.
    Mar 27 10:44:54 resin NetworkManager[905]: <info>  [1490611494.0413] Config: added 'ssid' value 'Tempura'
    Mar 27 10:44:54 resin NetworkManager[905]: <info>  [1490611494.0416] Config: added 'scan_ssid' value '1'
    Mar 27 10:44:54 resin NetworkManager[905]: <info>  [1490611494.0418] Config: added 'key_mgmt' value 'WPA-PSK'
    Mar 27 10:44:54 resin NetworkManager[905]: <info>  [1490611494.0419] Config: added 'auth_alg' value 'OPEN'
    Mar 27 10:44:54 resin NetworkManager[905]: <info>  [1490611494.0420] Config: added 'psk' value '<omitted>'
    Mar 27 10:44:54 resin NetworkManager[905]: <info>  [1490611494.0600] sup-iface[0xfb7208,wlan0]: config: set interface ap_scan to 1
    Mar 27 10:44:54 resin NetworkManager[905]: <info>  [1490611494.5164] device (wlan0): supplicant interface state: inactive -> authenticating
    Mar 27 10:44:54 resin NetworkManager[905]: <info>  [1490611494.5661] device (wlan0): supplicant interface state: authenticating -> associating
    Mar 27 10:44:54 resin NetworkManager[905]: <info>  [1490611494.6133] device (wlan0): supplicant interface state: associating -> 4-way handshake
    Mar 27 10:44:54 resin NetworkManager[905]: <info>  [1490611494.7784] device (wlan0): supplicant interface state: 4-way handshake -> completed
    Mar 27 10:44:54 resin NetworkManager[905]: <info>  [1490611494.7845] device (wlan0): Activation: (wifi) Stage 2 of 5 (Device Configure) successful.  Connected to wireless network 'Tempura'.
    Mar 27 10:44:54 resin NetworkManager[905]: <info>  [1490611494.7929] device (wlan0): state change: config -> ip-config (reason 'none') [50 70 0]
    Mar 27 10:44:54 resin NetworkManager[905]: <info>  [1490611494.8106] dhcp4 (wlan0): activation: beginning transaction (timeout in 45 seconds)
    Mar 27 10:44:54 resin NetworkManager[905]: <info>  [1490611494.8403] dhcp4 (wlan0): dhclient started with pid 1188
    Mar 27 10:44:55 resin dhclient[1188]: DHCPDISCOVER on wlan0 to 255.255.255.255 port 67 interval 3
    Mar 27 10:44:56 resin dhclient[1188]: DHCPREQUEST on wlan0 to 255.255.255.255 port 67
    Mar 27 10:44:56 resin dhclient[1188]: DHCPOFFER from 192.168.2.1
    Mar 27 10:44:56 resin dhclient[1188]: DHCPACK from 192.168.2.1
    Mar 27 10:44:56 resin NetworkManager[905]: <info>  [1490611496.3429] dhcp4 (wlan0):   address 192.168.2.75
    Mar 27 10:44:56 resin NetworkManager[905]: <info>  [1490611496.3483] dhcp4 (wlan0):   plen 24 (255.255.255.0)
    Mar 27 10:44:56 resin NetworkManager[905]: <info>  [1490611496.3515] dhcp4 (wlan0):   gateway 192.168.2.1
    Mar 27 10:44:56 resin NetworkManager[905]: <info>  [1490611496.3537] dhcp4 (wlan0):   server identifier 192.168.2.1
    Mar 27 10:44:56 resin NetworkManager[905]: <info>  [1490611496.3539] dhcp4 (wlan0):   lease time 86400
    Mar 27 10:44:56 resin NetworkManager[905]: <info>  [1490611496.3542] dhcp4 (wlan0):   nameserver '192.168.2.1'
    Mar 27 10:44:56 resin NetworkManager[905]: <info>  [1490611496.3543] dhcp4 (wlan0):   nameserver '8.8.8.8'
    Mar 27 10:44:56 resin NetworkManager[905]: <info>  [1490611496.3544] dhcp4 (wlan0): state changed unknown -> bound
    Mar 27 10:44:56 resin dhclient[1188]: bound to 192.168.2.75 -- renewal in 36601 seconds.
    Mar 27 10:44:56 resin NetworkManager[905]: <info>  [1490611496.4340] device (wlan0): state change: ip-config -> ip-check (reason 'none') [70 80 0]
    Mar 27 10:44:56 resin NetworkManager[905]: <info>  [1490611496.4519] device (wlan0): state change: ip-check -> secondaries (reason 'none') [80 90 0]
    Mar 27 10:44:56 resin NetworkManager[905]: <info>  [1490611496.4728] device (wlan0): state change: secondaries -> activated (reason 'none') [90 100 0]
    Mar 27 10:44:56 resin NetworkManager[905]: <info>  [1490611496.4785] manager: NetworkManager state is now CONNECTED_LOCAL
    Mar 27 10:44:56 resin NetworkManager[905]: <info>  [1490611496.5600] manager: NetworkManager state is now CONNECTED_GLOBAL
    Mar 27 10:44:56 resin NetworkManager[905]: <info>  [1490611496.5700] policy: set 'resin-sample' (wlan0) as default for IPv4 routing and DNS
    Mar 27 10:44:56 resin NetworkManager[905]: <info>  [1490611496.5709] dns-mgr: Writing DNS information to /sbin/resolvconf
    Mar 27 10:44:56 resin NetworkManager[905]: <info>  [1490611496.8558] device (wlan0): Activation: successful, device activated.

**Comment by willnewton** [comment]
@imrehg reports the generic beaglebone image 2.0.0 rev4 boots and associates to the wifi on BBGW.

**Comment by floion** [comment]
I still have this issue on a 2.0.0+rev2 beaglebone image
