### ISSUE TITLE
Jenkins builds don't build external forks

### ISSUE THREAD

**Issue by willnewton** [resin-os/resinos#263]
If an external contributor forks one of our repos the Jenkins build will fail, e.g.:

https://github.com/resin-os/meta-resin/pull/633

If we are going to build a successful community around resinOS we need to be able to streamline the process of accepting patches from external contributors.

**Comment by agherzan** [comment]
The current build scripts assume that all the sources are from branches in the targeted repository. We definitely need to add support for forks too.

**Comment by willnewton** [comment]
After a few experiments I think I have a way to fix this:

    Switch all yocto-<board> and meta-resin jobs to use:                                                                                                                                                                                                          
      Use refspec: +refs/heads/*:refs/remotes/origin/* +refs/pull/*:refs/remotes/origin/pr/*                                                                                                                                                                      
      Use Branch Specifier: ${ghprbActualCommit}                                                                                                                                                                                                                  
      Rename job parameter ghprbSourceBranch to ghprbActualCommit                                                                                                                                                                                                 
      Replace ghprbSourceBranch with ghprbActualCommit elsewhere in the config (e.g. build name)

This seems to work for single boards (e.g. resin-beaglebone) but needs integration with meta-resin which is trickier as it involves switching over all the jobs at once, which AFAIK has to be done manually.

**Comment by willnewton** [comment]
I'd like to get feedback on whether this seems feasible and/or correct.

Also is there a better way to roll a change like this out than asking everyone not to start builds and doing it all through the web UI?

@agherzan @lifeeth @brownjohnf

**Comment by brownjohnf** [comment]
@willnewton Hm, tough question. Our configs are all stored here: https://github.com/resin-io/resin-jenkins-config/tree/master/jobs, but there's no good way to make changes to that repo and pull it back down to Jenkins. When people have done this sort of thing in the past, I think they usually just use sed on jenkins itself. @lifeeth may have insight into that.

**Comment by willnewton** [comment]
This is now done. There's still some wrinkles to iron out - e.g. the job names look ugly for PRs, but hopefully its all fixable.

**Comment by willnewton** [comment]
This seems to be working now so I think this can be closed.
