### ISSUE TITLE
Improve website deployment procedure

### ISSUE THREAD

**Issue by craig-mulligan** [resin-os/resinos#272]
Last week (14/04/2017) we had a failed deploy, a few issues contributed.

* No deployment documentation.
* style and js scripts should do automatically cache busting with there build hash.
* (Assuming this is what happened), a missing `gh-token` caused a build to partially fail but it didn't exit with correct code and was still deployed.

Fixes: 
1. MV to the same deployment pipeline that resin docs has. 
2. Document deployment.
3. Automatically bump scripts with hash as query string.
4. Fix false positives in the build process.

**Comment by floion** [comment]
@craig-mulligan any progress on this? Or is it done?

**Comment by craig-mulligan** [comment]
@floion, no progress. I'll try get on it this week.

**Comment by craig-mulligan** [comment]
@floion `1`, `2` & `4` have been fixed with #332 and #333. 

I've move 3 into a separate issue.
