### ISSUE TITLE
Unify managed/unmanaged images

### ISSUE THREAD

**Issue by agherzan** [resin-os/resinos#274]
There will be only one image containing everything and based of config.json variables it will behave as a managed or unmanaged.

**Comment by agherzan** [comment]
Implementation details:

We will have an empty object in `config.json` called `resin_server`. This, for now, will switch in between managed and unmanaged images. In the future it will contain all the needed information for connectivity to resin cloud.

If `resin_server` doesn't exist in the json file, supervisor will start in offline mode. @pcarranzav , can confirm this mode exists and can you estimate how complicate is to switch the config flag on the one specified here?

prepare-openvpn service will not generate the vpn credentials file when these don't exist in the config.json. The openvpn service which depends on the prepare-openvpn, will start with a condition on the existence of the vpn credentials file. 

TBD: yocto build system default
TBD: prepare vpn create the credentials based on the existence on `resin_server`

**Comment by alexandrosm** [comment]
@agherzan can we please change the name of this field to something like
`management_services` or equivalent? can share context on flowdock.

-- 

*Alexandros Marinos*

Founder & CEO, Resin.io


+1 206-637-5498

@alexandrosm

**Comment by agherzan** [comment]
@alexandrosm Sure. But we need to decide on a name. Shall I use `management_services`?

**Comment by agherzan** [comment]
Done accordingly to https://github.com/resin-io/hq/pull/1077 and implemented in https://github.com/resin-os/meta-resin/pull/1028.
