### ISSUE TITLE
`/var/lib` is mounted as tmpfs

### ISSUE THREAD

**Issue by agherzan** [resin-os/resinos#280]
_From @petrosagg on October 9, 2016 6:6_

There is state that should be persisted in `/var/lib` that is currently lost during reboot due to the tmpfs mount. For example the systemd random-seed and the systemd clock file that helps maintain a monotonic clock.

```
./systemd/clock
./systemd/random-seed
./NetworkManager/dhclient6-9fc92dad-29a7-4de8-acf6-c09e95341029-wlan0.lease
./NetworkManager/dhclient6-wlan0.conf
./NetworkManager/seen-bssids
./NetworkManager/timestamps
./NetworkManager/dhclient-9fc92dad-29a7-4de8-acf6-c09e95341029-wlan0.lease
./NetworkManager/secret_key
./NetworkManager/dhclient-wlan0.conf
./NetworkManager/NetworkManager-intern.conf
./dropbear/authorized_keys
```

_Copied from original issue: resin-os/meta-resin#406_

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_247l)

**Comment by agherzan** [comment]
_From @petrosagg on October 9, 2016 6:13_

Also `/var/lib` includes `/var/lib/systemd/coredump` which could easily fill up RAM if enough programs crash

**Comment by floion** [comment]
ping @agherzan @willnewton on this

**Comment by agherzan** [comment]
The systemd part was implemented as part of https://github.com/resin-os/meta-resin/pull/662 .

dropbear - is currently persistent on disk and bindmounted over with copy as tmpfs at boot. I would say we can keep it as is for now. 

NetworkManager - needs to be worked on because it can get pretty big due to old leases. On my host I'm around 1M already used by 198 file from which 188 are leases.

I'll say this needs to be completed in the future but the high priority subtask was done.

**Comment by imrehg** [comment]
At least `NetworkManager/secret_key` needs to be persisted for [stable MAC randomization](https://blogs.gnome.org/thaller/tag/clone-mac-address/#stable) to work with NetworkManager. The other stuff might need to be kept (I guess `seen-bssids` and `timestamps`) might be better to keep. The rest, hm....

**Comment by floion** [comment]
The NetworkManager part here should be fixed by https://github.com/resin-os/meta-resin/pull/850
