### ISSUE TITLE
Update "latest version" in header on resinOS site 

### ISSUE THREAD

**Issue by alisondavis17** [resin-os/resinos#282]

**Comment by alisondavis17** [comment]
cc @craig-mulligan

**Comment by craig-mulligan** [comment]
@alisondavis17 what should it be? It currently reads `Latest version 2.0.0 | Affogato`

**Comment by alisondavis17** [comment]
oh, I guess it's up to date since the new versions we released are resinOS 2.0.0+rev5.dev etc.

**Comment by craig-mulligan** [comment]
Yea 👍, I think we stick with just the semver version. And leave the revs per board.
