### ISSUE TITLE
Include raspberrypi firmware which supports program_usb_boot_mode

### ISSUE THREAD

**Issue by agherzan** [resin-os/resinos#283]
<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_1izj)

**Comment by floion** [comment]
@agherzan can you confirm that on the bsp side we now have the firmware (version at least 20170405) that has support for program_usb_boot_mode ?

**Comment by floion** [comment]
I actually see this in meta-raspberrypi:

commit 19e9381dbcc379ee97c32ce8b5f01a4af7de6d6e
Author: Andrei Gherzan <andrei@gherzan.ro>
Date:   Fri Apr 14 21:10:53 2017 +0100

    firmware.inc: Bump to 20170405
    
    Signed-off-by: Andrei Gherzan <andrei@gherzan.ro>

So looks like we do have it. Closing this item
