### ISSUE TITLE
Release 1.26

### ISSUE THREAD

**Issue by agherzan** [resin-os/resinos#284]
For now we only plan it for RaspberryPi line.

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_1k3v)

**Comment by pcarranzav** [comment]
I think you meant 1.26? edited just in case

**Comment by agherzan** [comment]
Thanks @pcarranzav

**Comment by dfunckt** [comment]
@agherzan shouldn't this be closed now that 1.26 is in production? Just a heads up.

**Comment by agherzan** [comment]
Good point. Thanks @dfunckt
