### ISSUE TITLE
ResinOS_uEnv.txt is not migrated 

### ISSUE THREAD

**Issue by telphan** [resin-os/resinos#293]
The resin-image-flasher is not copying resinOS_uEnv.txt to internal memory to persist user modification to this file.

**Comment by floion** [comment]
I don't think this is a bug.
I believe what we intended was that users could create this file in the boot partition if they needed to.
So by default, this file does not exist. If users need it, they should create it.

**Comment by telphan** [comment]
@floion This is specific for resin-image-flasher, if a user decides to create this file then this file should be copied in the flashed image.

**Comment by floion** [comment]
Yes, but for what purpose the user creates the file during provisioning?

**Comment by telphan** [comment]
How else would a user modify the u-boot environment? e.g. inject custom cmdline options.

**Comment by floion** [comment]
Custom cmdline needed for the provisioning step? I can't think of anything now that is absolutely needed in the provisioning step but I guess it makes it easier for after provisioning

**Comment by telphan** [comment]
A specific example is with a user that wants to use a display with the artik and in order to configure it he needs to pass some parameters to the kernel (to set display's resolution). He obviously wants to use this image for multiple devices, so the step is need when provisioning.
