### ISSUE TITLE
Update beaglebone kernel to version 4.9

### ISSUE THREAD

**Issue by floion** [resin-os/resinos#296]
Suggestion would be to use tag 4.9.27-ti-r33
Speaking of which @agherzan and @petrosagg , do we need to use the rt kernels? We currently use a rt kernel for the beaglebone and not sure we need to.
If we stick to the rt kernel, then suggestion is to move to tag 4.9.27-ti-rt-r33

**Comment by agherzan** [comment]
I personally don't have any requirements in that regards. @petrosagg to confirm.

**Comment by telphan** [comment]
Waiting confirmation on this.

**Comment by floion** [comment]
@telphan any update on this?

**Comment by floion** [comment]
My decision is that we don't use the rt kernel and go with the regular kernel

**Comment by agherzan** [comment]
I agree with @floion

**Comment by telphan** [comment]
@floion I will follow your decision then. There is no other comment here.

**Comment by floion** [comment]
Updated kernel to 4.9.27-ti-r33
