### ISSUE TITLE
btrfs file system unmounts itself after a brief delay

### ISSUE THREAD

**Issue by agherzan** [resin-os/resinos#30]
_From @lorenzo-stoakes on August 10, 2016 9:23_

After a short delay from user app start the btrfs file system unmounts for no obvious reason, resulting in all units that depend on the mount exiting, i.e. supervisor, docker, openvpn.

This renders the device 'soft-bricked' and therefore unusable. Additionally, attempts to mount the btrfs partition to `/mnt/data` result in no error, no dmesg entries but no mounting actually taking place. Attempting to mount the file system to another path succeeds, though any attempt to 'cheat' by symlinking, etc. results in the same issue recurring.

This has been reproduced on production (1.1.0 fido) and tip (1.8.0) resin OS.

_Copied from original issue: resin-os/resin-ts#34_

**Comment by willnewton** [comment]
No further development is planned for this board.
