### ISSUE TITLE
Normal provisioning without deltas

### ISSUE THREAD

**Issue by agherzan** [resin-os/resinos#300]
# Description 
Provision a device and check that supervisor works well without and with deltas

# Steps to reproduce issue 
Provision a board on a test application. Ensure RESIN_SUPERVISOR_DELTA config var is *not* set to "1".
Push a simple application (e.g. a loop that prints to console).
Once updated, test LED blink and Web Terminal.
Set an environment variable FOO=bar.

# Expected result 
Device should appear on the dashboard.
Device should download the application and run it.
LED should blink. (if available)
Web Terminal should open and allow running commands.
When the env var is set, the device should update the application to run with the new var. Opening a web terminal and running "env" should show the variable is correctly set.

# Actual result 
Resin logo not visible for reboot/shutdown. It is visible at start-up however but once the board has booted up it disappears.

# Other information 
- Reported by: Florin Sarbu 

- Test configuration: RaspberryPi 3 

- Test case number: TC09 

- Test run: [https://resinio.testlodge.com/projects/16238/runs/267416?tab=2&run_section_id=326555&executed_case_id=11789993#executed_case_11789993](https://resinio.testlodge.com/projects/16238/runs/267416?tab=2&run_section_id=326555&executed_case_id=11789993#executed_case_11789993)

**Comment by floion** [comment]
Faulty issue. Closing
