### ISSUE TITLE
RESIN_HOST_LOG_TO_DISPLAY broken on 1.x?

### ISSUE THREAD

**Issue by Page-** [resin-os/resinos#308]
The "check your resin.io dashboard" message still seems to appear when setting RESIN_HOST_LOG_TO_DISPLAY to 0 on v1.26.0:

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_250l)

**Comment by floion** [comment]
cc @agherzan @willnewton

**Comment by agherzan** [comment]
Is this reproducible on 2.X? Could you please check, @Page- ?

**Comment by imrehg** [comment]
Anything new with this?

**Comment by agherzan** [comment]
Closing for now as we don't plan to investigate this on the 1.x line.
