### ISSUE TITLE
Intel NUC can't use custom splashscreen  

### ISSUE THREAD

**Issue by Seungja** [resin-os/resinos#316]
### Steps to reproduce issue
- Replace the splash/resin-logo.png in the boot partition of a **resinOS** _(2.0.4+rev1 as the time of this writing)_ **image**.
- Boot a **Intel NUC** with that image and the **custom splashscreen** loads fine the first time.
- After the **Post Provisioning** step (and removing the usb); it loads default **Resin Logo** Splash from there onwards.

### Expected result
- **Custom splashscreen** to be persistent between updates & deployments.

### Actual result
- The **splashcreen** reverts to the default (resin logo).

### Other information
- Tested on **Intel NUC** nuc7i3bnk &  nuc6i3syk Units
- Tested on **resinOS** 2.0.0+rev3 & 2.0.4+rev1, prod & dev variants.

**Comment by agherzan** [comment]
Hi @Seungja . Thanks for the report. We will investigate and come back with information.

**Comment by Seungja** [comment]
just a follow up, i just tested Resin OS 2.0.6+rev1 and still had the same issues so i tried to SSH into a device and i noted that on the Boot partition somehow duplicates the splash folder with the custom boot logo in it, so now we got:

```
Resin-Boot //Root
• EFI
• config.json
• device-type.json
• image-version-info
• resin-image
• resinos.fingerprint
+ splash
  • resin-logo.png //the original resin boot logo
  + splash
    • resin-logo.png //the custom boot logo
• system-connections
• vmlinuz
```
probably you guys already know it but i though i should post it here just in case.

**Comment by floion** [comment]
Hi. So indeed, this seems like a glitch from the flasher script. Haven't yet had time to look into this, will try for the 2.0.8 release.
Thanks for the follow-up

**Comment by agherzan** [comment]
@Seungja https://github.com/resin-os/meta-resin/pull/730 this should fix the bug you reported. Would you be able to give it a try?

**Comment by Seungja** [comment]
Just confirming that [resin-os/meta-resin#730](https://github.com/resin-os/meta-resin/pull/730) & **Resin OS 2.0.9** fixes the issue.

**Comment by agherzan** [comment]
Thanks @Seungja for testing this.
