### ISSUE TITLE
/sys/devices/platform/bone_capemgr not available on the Beaglebone Blue

### ISSUE THREAD

**Issue by shaunmulligan** [resin-os/resinos#322]
On the Beaglebone Blue devices it seems `/sys/devices/platform/bone_capemgr/slots` does not exist, this means that libraries like https://github.com/theoctal/octalbonescript will fail, and I think general cape loading will fail.

This [ADC example project](https://github.com/resin-io-projects/beaglebone-adc-node) works on the BBBlack, but fails on the BBBlue.

**Comment by willnewton** [comment]
It looks like the Blue does not support the cape manager:

```
For the Blue, the current plan is to not use the cape manager.  Instead every connector should default to it’s labeled default.  On the backend, I’m making sure alternative options are avaiable thru “config-pin”
```
