### ISSUE TITLE
Bluetooth

### ISSUE THREAD

**Issue by agherzan** [resin-os/resinos#324]
# Description 
Test internal Bluetooth device on Raspberry Pi Zero Wireless

# Steps to reproduce issue 
Have a new Raspberrypi Zero Wireless device provisioned or use one that is already provisioned with an image for this release that has no "Device Configuration" variables configured.
Have an activated and visible Bluetooth device around you.
Push to the device's application the one located at https://github.com/resin-io-playground/rpi3-ble .

# Expected result 
Check the dashboard's log of the pushed app. Last log messsage should be: TEST PASSED

# Actual result 
08.06.17 19:06:16 (+0200) Testing bluetooth on RPI3. Make sure you have a bluetooth device enabled and visible.                                                            
08.06.17 19:06:16 (+0200) Attaching hci0...                                                                                                                                
08.06.17 19:06:16 (+0200) bcm43xx_init                                                                                                                                     
08.06.17 19:06:46 (+0200) Initialization timed out.                                                                                                                        
08.06.17 19:06:46 (+0200) First try failed. Let's try another time.                                                                                                        
08.06.17 19:06:46 (+0200) bcm43xx_init                                                                                                                                     
08.06.17 19:06:46 (+0200) Patch not found for BCM43430A1, continue anyway                                                                                                  
08.06.17 19:06:46 (+0200) Set Controller UART speed to 921600 bit/s                                                                                                        
08.06.17 19:06:46 (+0200) Device setup complete                                                                                                                            
08.06.17 19:06:46 (+0200) Bring hci0 up...                                                                                                                                 
08.06.17 19:06:46 (+0200) Scan for devices...                                                                                                                              
08.06.17 19:06:57 (+0200) Test finished. App configured to not exit. Restart the app if you want to retest.                                                                
08.06.17 19:06:57 (+0200) TEST FAILED

# Other information 
- Reported by: Michal Mazurek 

- Test configuration: RaspberryPi Zero Wireless 

- Test case number: TC21 

- Test run: [https://resinio.testlodge.com/projects/16238/runs/270571?tab=2&run_section_id=333257&executed_case_id=11908778#executed_case_11908778](https://resinio.testlodge.com/projects/16238/runs/270571?tab=2&run_section_id=333257&executed_case_id=11908778#executed_case_11908778)

**Comment by floion** [comment]
@michal-mazurek this test case needs to be redone specifically for the rpi zero wireless
Can you do that since you have the board with you?

**Comment by floion** [comment]
@michal-mazurek any progress?

**Comment by michal-mazurek** [comment]
The rpi0 image, when installed on a rpi0w, comes with the required bluetooth tools, however lacks the required firmware file. It seems the tools get installed, but not via our recipe, which also changes the firmware path from /etc/firmware/ to /lib/firmware/.

Copying /lib/firmware/brcm/BCM43430A1.hcd from a rpi3 to /etc/firmware/brcm/BCM43430A1.hcd on a rpi0w makes it work.

**Comment by floion** [comment]
This looks like should be handled from the BSP layer

**Comment by floion** [comment]
Fixed in release v2.0.6+rev3
