### ISSUE TITLE
Ralink RT5572 based USB wifi dongle not working with the UP board

### ISSUE THREAD

**Issue by floion** [resin-os/resinos#325]
<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_1vgn)

**Comment by telphan** [comment]
Needs merge and release on (https://github.com/resin-os/resin-up-board)

**Comment by floion** [comment]
fixed by https://github.com/resin-os/meta-resin/pull/705

**Comment by floion** [comment]
PR merged. This will be available in meta-resin release v2.0.7
