### ISSUE TITLE
User configurable NTP servers

### ISSUE THREAD

**Issue by shaunmulligan** [resin-os/resinos#328]
There are times when users want to use their own custom or internal NTP servers. We should allow them to add this type of configuration to the `config.json`

**Comment by alexandrosm** [comment]
agreed

-- 

*Alexandros Marinos*

Founder & CEO, Resin.io


+1 206-637-5498

@alexandrosm

**Comment by willnewton** [comment]
Closed by https://github.com/resin-os/meta-resin/pull/737
