### ISSUE TITLE
User configurable DNS servers

### ISSUE THREAD

**Issue by shaunmulligan** [resin-os/resinos#329]
Often users need to configure specific DNS for their devices. We should enable this feature by allowing them to add this to the `devices` config.json.

**Comment by willnewton** [comment]
@shaunmulligan do you have a feel for how this should work i.e. is the configured DNS server the only one that is ever queried? does it prefer, fallback to or ignore DHCP provided DNS?

**Comment by willnewton** [comment]
I've implemented this feature using additional dnsmasq server lines which means that DHCP discovered DNS would be tried after configured DNS. Let me know if that sounds ok.

The PR is currently blocked on the NTP PR which modifies some of the same files.

**Comment by agherzan** [comment]
I'll let @shaunmulligan to weight in here but for me this is what I thought as being the solution too.

**Comment by shaunmulligan** [comment]
@willnewton yeah, this sounds good to me 👍

**Comment by willnewton** [comment]
Closed by https://github.com/resin-os/meta-resin/pull/750
