### ISSUE TITLE
resin-filesystem-expand fails if the fs contains errors which are recoverable

### ISSUE THREAD

**Issue by floion** [resin-os/resinos#331]
From e2fsck man page:
EXIT CODE
       The exit code returned by e2fsck is the sum of the following conditions:
            0    - No errors
            1    - File system errors corrected
            2    - File system errors corrected, system should
                   be rebooted
            4    - File system errors left uncorrected
            8    - Operational error
            16   - Usage or syntax error
            32   - E2fsck canceled by user request
            128  - Shared library error

When e2fsck above exits with exit code 1 for example, that should not be treated as error.

We have a few options:

1 - get rid of set -e altogether as this is a small script and commands we run in it are depending on one another
2 - surround the e2fsck call with set +e and back again with set -e
3 - handle the exit code of e2fsck and consider exit status 0, 1 and maybe 2 as valid and acceptable for us and based on these accepted values we won't exit the resin-filesystem-expand with an error
with something like:
    `e2fsck_exit_code=0; e2fsck -y $DATA_PARTITION || e2fsck=$?
    if [ e2fsck_exit_code = 0] || [ e2fsck_exit_code = 1 ] || [ e2fsck_ext_code = 2 ] ; then resize2fs -f $DATA_PARTITION; else exit 1; fi `

**Comment by shaunmulligan** [comment]
Do we currently have logic that does the reboot if efsck exits with `2`?

**Comment by floion** [comment]
No, the script will just exit at the point where e2fsck returns a non-zero exit code.

**Comment by willnewton** [comment]
Closed by https://github.com/resin-os/meta-resin/pull/757
