### ISSUE TITLE
Remove PACKAGE_CLASSES from board configs

### ISSUE THREAD

**Issue by agherzan** [resin-os/resinos#337]
After https://github.com/resin-os/meta-resin/pull/694 , meta-resin defines and relies on the configuration of PACKAGE_CLASSES . It will, as well, warn the user if it is set to something that resinOS is not expected to work with (currently ipk is the configuration we are using). Before this change, the package configuration was set in the sample build config in each board repository.

**Comment by floion** [comment]
Done. Closing this item
