### ISSUE TITLE
Provision on Ethernet

### ISSUE THREAD

**Issue by agherzan** [resin-os/resinos#34]
_From @telphan on July 1, 2016 14:46_

@agherzan commented on [Fri Jul 01 2016](https://github.com/resin-os/meta-resin/issues/162)
# Description

Provision the device using the Ethernet port.
# Steps to reproduce issue

Download Device OS
Network Connection: Ethernet
Download OS file
# Expected result

Device should appear in the application's dashboard
# Other information

Reported by: Theodor Gherzan 

Test configuration: TS7700 

Test case number: TC01 

Test run: [https://resinio.testlodge.com/projects/16238/runs/216494?tab=2&run_section_id=220109&executed_case_id=10168350#executed_case_10168350](https://resinio.testlodge.com/projects/16238/runs/216494?tab=2&run_section_id=220109&executed_case_id=10168350#executed_case_10168350)

_Copied from original issue: resin-os/resin-ts#26_

**Comment by willnewton** [comment]
No further development is planned for this board.
