### ISSUE TITLE
Boot/reboot/shutdown splash screen (artik 710)

### ISSUE THREAD

**Issue by agherzan** [resin-os/resinos#340]
# Steps to reproduce issue 
Connect to the HDMI connected to a monitor
Boot the device

# Expected result 
Resin logo splash screen should be visible

# Actual result 
LVDS screen not displaying any output
HDMI output works as expected

# Other information 
- Reported by: Florin Sarbu 

- Test configuration: Artik 710 

- Test case number: TC07 

- Test run: [https://resinio.testlodge.com/projects/16238/runs/273636?tab=2&run_section_id=341838&executed_case_id=12041070#executed_case_12041070](https://resinio.testlodge.com/projects/16238/runs/273636?tab=2&run_section_id=341838&executed_case_id=12041070#executed_case_12041070)

**Comment by floion** [comment]
Closing as hdmi output is working
