### ISSUE TITLE
Running the barys build script with --dry-run does not expose bitbake

### ISSUE THREAD

**Issue by tiniuclx** [resin-os/resinos#350]
If you execute a dry run using the script as you would expect, by running `./barys --dry-run` , you cannot execute `bitbake` and therefore you cannot build resinOS. 

This bug is caused by the fact that running a script via  `./` executes it in a new shell, isolated from the one in which the command was written. The bitbake command is exposed via `source oe-init-build-env`, _inside the shell it is ran in_. Once barys finishes executing it exits, closes the shell that was created for it, _the shell in which bitbake was exposed_. This results in the user not being able to `bitbake` anything, in spite of the fact that this is what the script suggests as the next step.

My workaround was commenting out the final line of the script, `exit $EXIT_CODE` , and running barys as follows: `source barys`. The `source` keyword ensures a script runs in the current environment. This means that everything the script changes about the environment remains there after the it finishes execution. Removing `exit` is necessary because otherwise the shell would simply quit. A more robust solution would obviously be preferred, but this is what I could hack together to get it running as intended.

**Comment by agherzan** [comment]
Hi @tiniuclx,

Thanks for getting in contact with us. There is a misunderstanding on what `--dry-run` was designed to do. The intention of this mode is not to get you in a build environment but only create a build directory with configuration. It is expected that afterwards a `source layers/poky/oe-init-build-env build` command will be needed.

Hopefully this clarifies it.

**Comment by tiniuclx** [comment]
Hello Andrei,

Thank you for your reply. I've actually been getting that impression over the past few days, after familiarising myself with Yocto and how Resin OS uses it. I still believe it would be helpful if this was stated in the documentation, or within the prompts you get while running `barys` .

Thanks once more for your help.

**Comment by agherzan** [comment]
I raised a PR which should clarify this. Please take a look: https://github.com/resin-os/resin-yocto-scripts/pull/86 .

**Comment by tiniuclx** [comment]
Thank you! I had a look, the proposed change would be more than enough to clarify the proper usage.

**Comment by agherzan** [comment]
I'm glad it does @tiniuclx . Cheers!
