### ISSUE TITLE
Raspberry Pi2 device image not found

### ISSUE THREAD

**Issue by stuartm2** [resin-os/resinos#351]
Hi guys.  The link to the device image for Raspberry Pi2 from https://resinos.io/#downloads isn't working.  Pi1 and Pi3 links are fine.  I've tried various permutations of the Pi2 link to no avail - they all lead to the Amazon AWS "not found" page.

**Comment by craig-mulligan** [comment]
@stuartm2 Thanks for letting us know, there didn't seem to be a rpi2 rev3 uploaded for some reason, still figuring out why but I've fixed the link with #352.
