### ISSUE TITLE
REQUIRED_DISTRO_FEATURES += " systemd" breaks with yocto pyro

### ISSUE THREAD

**Issue by floion** [resin-os/resinos#362]
Having https://github.com/resin-os/meta-resin/blob/master/meta-resin-common/classes/resin-sanity.bbclass#L29

is breaking with yocto pyro. This change needed in the first place also

`inherit distro_features_check`

in resin-sanity.bbclass. Without this inheritance, bitbake complains:

> ERROR: Nothing RPROVIDES 'nativesdk-glibc' (but /home/florin/builds/resin-odroid/build/../layers/poky/meta/recipes-core/meta/uninative-tarball.bb RDEPENDS on or otherwise requires it)
ERROR: nativesdk-glibc was skipped: missing required distro feature 'systemd' (not in DISTRO_FEATURES)

But even after adding that inheritance, bitbake complains about random packages(it's not always parted-native that complains, subsequent build attemp will make bitbake complain about a different package):

ERROR: parted-native was skipped: missing required distro feature 'systemd' (not in DISTRO_FEATURES)

This can be reproduced by trying to build odroid-xu4 using this PR https://github.com/resin-os/resin-odroid/pull/43 in which one should manually update the meta-resin submodule to version v2.1.0 before starting the build

**Comment by willnewton** [comment]
I opened a WIP PR here: https://github.com/resin-os/meta-resin/pull/783

If this approach still doesn't work it may be best to just remove the line completely.

I haven't been able to test this myself as the build fails in some obscure fashion with the go recipe.

**Comment by floion** [comment]
@willnewton , the way you can test this, is to temporarily remove the go devtools recipes we have in meta-resin recipes and rely on the ones from poky.
I think that anyway we should try and move away from our go recipes and rely on the poky go recipes

**Comment by willnewton** [comment]
This is now fixed as part of the Pyro support work.
