### ISSUE TITLE
Kernel logo

### ISSUE THREAD

**Issue by agherzan** [resin-os/resinos#37]
_From @agherzan on April 26, 2016 11:6_

@agherzan commented on [Fri Feb 12 2016](https://github.com/resin-os/meta-resin/issues/10)
# Steps to reproduce issue

Connect to the HDMI connected to a monitor
Boot the device
# Expected result

The tux (linux) logos should not be visible on the screen
# Actual result

nothing on screen
# Other information

Reported by: Shaun Mulligan 

Test configuration: Parallella 

Test case number: TC08 

Test run: [https://resinio.testlodge.com/projects/16238/runs/192879?tab=2&run_section_id=168782&executed_case_id=9333897#executed_case_9333897](https://resinio.testlodge.com/projects/16238/runs/192879?tab=2&run_section_id=168782&executed_case_id=9333897#executed_case_9333897)

_Copied from original issue: resin-os/resin-parallella#6_

**Comment by willnewton** [comment]
No further development is planned for this board.
