### ISSUE TITLE
UP board: No GPU acceleration

### ISSUE THREAD

**Issue by imrehg** [resin-os/resinos#370]
The latest `2.2.0+rev1` does not seem to have GPU acceleration. As tested by @curcuz, every GPU flag is disabled and no HW acceleration is detected by chromium.

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_24ub)

**Comment by floion** [comment]
@imrehg can this be moved to resin-up-board and have Theodor assigned please?

**Comment by imrehg** [comment]
@floion reopened issue there and assigned.

**Comment by floion** [comment]
Thanks, closing this item here and following up here: https://github.com/resin-os/resin-up-board/issues/26
