### ISSUE TITLE
resin-uboot implementation - Test root partition switch

### ISSUE THREAD

**Issue by agherzan** [resin-os/resinos#372]
# Description 
This test is aimed at verifying the root partition switch functionality from partition rootA to partition rootB

# Steps to reproduce issue 
Clone the test git repository:
_'git clone https://github.com/resin-os/resinos-tests-legacy'_

1. Execute test for the first time::

_'cd resinos-tests && ./run-test -u <UUID> -s <RESIN_MANAGEMENT_SERVER> -t <TEST_NAME>'_

where UUID above is the UUID of the tested device displayed in the dashboard, RESIN_MANAGEMENT_SERVER is either _'resin'_ or _'resinstaging'_ (assuming you have the ssh aliasing created as resin to point to resin production and resinstaging to point to resin staging) and TEST_NAME specifies the test to be run. For example, resin_root_part_bbb can be used for all uboot based boards. See the _'tests/all/resin_root_part'_ directory for all root partition switch tests.

2. Execute test for the second time:

_'./run-test -u <UUID> -s <RESIN_MANAGEMENT_SERVER> -t <TEST_NAME>'_

# Expected result 
1. First execution of the test should yield output similar to the following:

[000000000][LOG]The following tests will be ran:
[000000000][LOG]   /resinos-tests/tests/all/resin_root_part/resin_root_part_bbb
[000000000][LOG]Transfering helpers on target...

[000000007][LOG][resin_root_part_bbb] Transfering test on target...
[000000015][LOG][resin_root_part_bbb] Running on target...
Warning: Permanently added '[a8a34869694a550991f2a5f269f79824.vpn]:22222' (RSA) to the list of known hosts.
[INFO] INFO copying root partition from /dev/mmcblk0p2 to /dev/mmcblk0p3...
312+0 records in
312+0 records out
327155712 bytes (327 MB, 312 MiB) copied, 34.1924 s, 9.6 MB/s

Killed by signal 1.
[000000055][LOG]Test results
[000000055][LOG]Failed tests: 0
[000000055][LOG]Total tests : 1

The board shall reboot. Wait until it appears online in the dashboard and proceed to step 2 bellow.

2. Second execution of the should yield output similar to:

[000000000][LOG]The following tests will be ran:
[000000000][LOG]   /resinos-tests/tests/all/resin_root_part/resin_root_part_bbb
[000000000][LOG]Transfering helpers on target...

[000000008][LOG][resin_root_part_bbb] Transfering test on target...
[000000016][LOG][resin_root_part_bbb] Running on target...
Warning: Permanently added '[a8a34869694a550991f2a5f269f79824.vpn]:22222' (RSA) to the list of known hosts.
[PASSED] OK
Killed by signal 1.

[000000022][LOG]Test results
[000000022][LOG]Failed tests: 0
[000000022][LOG]Total tests : 1

# Actual result 
Looks like no HUP support? No tests at least, and the meta-artik repo don't seem to have the patch.

# Other information 
- Reported by: Gergely Imreh 

- Test configuration: Artik 520 

- Test case number: TC24 

- Test run: [https://resinio.testlodge.com/projects/16238/runs/276578?tab=2&run_section_id=350019&executed_case_id=12174222#executed_case_12174222](https://resinio.testlodge.com/projects/16238/runs/276578?tab=2&run_section_id=350019&executed_case_id=12174222#executed_case_12174222)

**Comment by floion** [comment]
@imrehg can this be closed now?

**Comment by imrehg** [comment]
@floion yes, sorry. Updated in testlodge only.
