### ISSUE TITLE
TS4900's kernel panics after the shutdown performed by the flasher image

### ISSUE THREAD

**Issue by telphan** [resin-os/resinos#376]
<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_26jz)

**Comment by floion** [comment]
Wrong Front link.
@telphan were we able to still reproduce this panic at shutdown when flashing? I recall this was fixed quite a while ago

**Comment by floion** [comment]
This issue should be in the board repository

**Comment by telphan** [comment]
Re-opened here: https://github.com/resin-os/resin-ts/issues/110
