### ISSUE TITLE
[ts4900] Update kernel and aufs patches

### ISSUE THREAD

**Issue by telphan** [resin-os/resinos#377]

**Comment by floion** [comment]
ts4900 is now on overlayfs so no need to update the aufs patches.
Solely the kernel

**Comment by floion** [comment]
@telphan is this still needed? Did you follow-up on this?

**Comment by telphan** [comment]
I do not think this is still needed.

**Comment by floion** [comment]
Please investigate and then close if indeed it is not needed anymore

**Comment by telphan** [comment]
The move to overlayfs makes this ticket obsolete.
