### ISSUE TITLE
Use a bridge interface for dnsmasq to listen on

### ISSUE THREAD

**Issue by pcarranzav** [resin-os/resinos#408]
Currently we use iptables rules on [an ExecStartPost in the docker service](https://github.com/resin-os/meta-resin/blob/master/meta-resin-common/recipes-containers/docker/docker/docker.service#L14) to make containers trying to use the docker bridge be able to have DNS. This will break in multicontainer, and also breaks when a container with host networking is running docker-in-docker (resin-io/hq#967).

To make this more reliable, we can instead do the following:
* Before starting dnsmasq, another service (we can call it prepare-dnsmasq.service?) creates a bridge interface (maybe called `resin-dns`?), and gives it an IP address (for instance, we could use 10.114.102.1 to make it close to our default docker bridge without causing conflicts). In my experiments on a resinOS device, I've succeeded at doing this simply by doing:
```
ip link add name resin-dns type bridge
ip link set resin-dns up
ifconfig resin-dns 10.114.102.1
```
* In the [dnsmasq service](https://github.com/resin-os/meta-resin/blob/master/meta-resin-common/recipes-connectivity/dnsmasq/files/dnsmasq.conf.systemd#L8), we change the listen address (`-a`) to the address of the bridge.
* We change the host's [resolv.conf](https://github.com/resin-os/meta-resin/blob/master/meta-resin-common/recipes-connectivity/dnsmasq/files/resolv.conf#L2) to use the bridge address as nameserver.
* We change the docker service to use the bridge address as DNS (with `--dns`) and remove the `iptables` rule creation.

This should make all containers, plus all host services, correctly use dnsmasq via the bridge to resolve domains.
Special care should be taken in the prepare-dnsmasq.service so that service restarts do not cause multiple attempts at creating the bridge.

**Comment by petrosagg** [comment]
Can dnsmasq listen on both the localhost and the bridge interface?

**Comment by pcarranzav** [comment]
@petrosagg yes, I think so - but is there a benefit to it?

**Comment by pcarranzav** [comment]
afaik we'd only need to specify `-a "127.0.0.2,10.114.102.1"` (haven't tried it though)

**Comment by petrosagg** [comment]
There is no reason for the hostOS traffic to be going through the bridge. The benefit is less things need to go wrong for the host to not be able to resolve

**Comment by petrosagg** [comment]
Also, since we use the bridge now we can use the normal localhost address `127.0.0.1` instead of `127.0.0.2`

**Comment by pcarranzav** [comment]
Alright, yeah, makes sense to listen on both then.
As for the change to 127.0.0.1 - what was the original reason for using 127.0.0.2?

**Comment by agherzan** [comment]
Implemented. Will be pushed as part of the balena PR. https://github.com/resin-os/meta-resin/pull/902

**Comment by floion** [comment]
@pcarranzav @petrosagg the reason we were using 127.0.0.2 was:

dnsmasq: Listen on 127.0.0.2 instead of 127.0.0.1
    
    We change dnsmasq to listen on 127.0.0.2 so that user containers can run
    their own dns cache and forwarders without interfering with dnsmasq on the host.

**Comment by pcarranzav** [comment]
Thanks @floion - in that case it sounds like we still need to stay on 127.0.0.2, cause containers with host networking will still need that
