### ISSUE TITLE
[website] Automatically load latest unmanaged OS versions

### ISSUE THREAD

**Issue by LucianBuzzo** [resin-os/resinos#414]
This should be straightforward, as we can query the files available from S3

**Comment by LucianBuzzo** [comment]
Since the OS images bucket is publicly accessible, we can use a simple get request to list the contents:
```
http://s3.amazonaws.com/resin-production-img-cloudformation/?prefix=resinos/raspberrypi3
```

Here is the documentation for the parameters we can use https://docs.aws.amazon.com/AmazonS3/latest/API/v2-RESTBucketGET.html

**Comment by Shou** [comment]
Yeah, we used to pull releases from s3 – check [this commit diff][1] where it was changed and that might help out with this

[1]: https://github.com/resin-io/etcher-homepage/commit/4a0c871f5e2fbd08e4aa7289b4ed9a50d4b22e99#diff-d465257d785227c03e786e4df3d23163

**Comment by LucianBuzzo** [comment]
We can fetch the latest unmanaged OS versions from S3, but at the moment the `latest` text file is not publicly readable.

**Comment by lurch** [comment]
On Etcher we don't have a `latest` file, we just assume that the version with the greatest semver is the latest release. (which means if we want to 'pull' a release, we also need to delete it from S3)
But I've obviously got no idea if such a simple approach would work with the complexity of all the resinOS releases!

**Comment by LucianBuzzo** [comment]
I've opened an issue to make the `latest` file publicly readable https://github.com/resin-os/resin-yocto-scripts/issues/108

**Comment by lurch** [comment]
This also tangentially relates to #406

**Comment by lekkas** [comment]
HQ: https://github.com/resin-io/hq/issues/1180

**Comment by LucianBuzzo** [comment]
@lekkas I think we may be able to close this issue, unless there are additional requirements that my PR doesn't satisfy?

**Comment by lekkas** [comment]
@LucianBuzzo as far as I can see this addresses the report in HQ, so feel free to close the issue. Thanks!
