### ISSUE TITLE
meta-up-board points to no-longer-existing-commit for resin-up-board 2.9.6+rev1

### ISSUE THREAD

**Issue by imrehg** [resin-os/resinos#416]
Looks like they've rewritten history:

resin-up-board references meta-up-board with this commit and history: https://github.com/emutex/meta-up-board/commits/fde6a73a3b95e6aa873952399ec9420b6eda3160 (cannot check out)

The accessible commit is this, which seems to be the same, just the penultimate commit redone in Jan 8?
https://github.com/emutex/meta-up-board/commits/fb7470d42a289d37f026674665f6b10b4b0ec74b (can check out)

**Comment by agherzan** [comment]
We should update that layer to the current HEAD of the pyro branch to fix this issue for now (https://github.com/emutex/meta-up-board/commits/pyro). As well I would open a discussion with the maintainer to figure out why this happened and if this is a common practice in their development. Just to see if this if likely to happen again. @spanceac can you take this in your queue?
