### ISSUE TITLE
Download links are outdated on resinos.io

### ISSUE THREAD

**Issue by adriengibrat** [resin-os/resinos#424]
Hi,

Lot of download links are outdated on https://resinos.io, by ex :

- Raspberry Pi links to download on the website: resinOS 2.3.0+rev1.dev  (17 Aug 2017) & resinOS 2.2.0+rev1.dev (31 Jul 2017) but [github latest version](https://github.com/resin-os/resin-raspberrypi/releases) is 2.9.6+rev1 
- Odroid C1/C1+ & Odroid XU4 links to download on the website: resinOS 2.0.0-beta.1 (11 Oct 2016) but [github latest version](https://github.com/resin-os/resin-odroid/releases) is 2.9.7+rev1

Unfortunatly, on github release, only the source files are available to download, not the actual image build :/

**Question** Is there a link to download recent images ? I'm interested in a recent Odroid XU4, with a docker version > 1.13.0 (do you feel my pain ?! ;))

**Suggestion** use [github release API](https://developer.github.com/v3/repos/releases/#upload-a-release-asset) to upload build images of each release. 

On https://files.resin.io because it's a S3 bucket it is hard to list files (N.B. https://files.resin.io still list old /images/... path despite #106).

This solution could also solve #161 issue by the way.

**Comment by lurch** [comment]
Duplicate of #414 ?

**Comment by lurch** [comment]
And see also #423 - looks like the site will be getting updated soon anyway, even before #414 gets implemented.

**Comment by adriengibrat** [comment]
:+1: great news! And now I can look for an recent odroid image ;)

**Comment by adriengibrat** [comment]
No odroid in https://github.com/resin-os/resinos/pull/421/files nor http://s3.amazonaws.com/resin-production-img-cloudformation/?prefix=resinos/odroid :cry:

**Comment by lurch** [comment]
https://resinos.io/ has now been updated, so this issue can be closed @LucianBuzzo 

@agherzan Do you know if there are any plans to produce an updated unmanaged resinOS build for the Odroid XU4 ?

**Comment by shaunmulligan** [comment]
@lucianbuzzo I believe @floion is about to release one

**Comment by floion** [comment]
@lurch odroid-xu4 will be deployed to production soon

**Comment by adriengibrat** [comment]
Actually, I discovered the staging URL https://dashboard.resinstaging.io where I can download the most recent builds ;)

**Comment by lurch** [comment]
@adriengibrat Be aware that images downloaded from resinstaging.io are managed builds, whereas images downloaded from resinos.io are unmanaged builds.

**Comment by adriengibrat** [comment]
Yes, I'm [aware of the difference](https://docs.resin.io/understanding/understanding-devices/2.x/) The dev edition are still managed, but allow local hacking ;)

**Comment by lurch** [comment]
Oh, that's an interesting point...
@shaunmulligan From what I understand according to https://docs.resin.io/understanding/understanding-devices/2.x/#variants-of-resinos , the images of resinOS downloadable from https://resinos.io/ are unmanaged / standalone versions, and according to that docs page they ought to be named like `2.0.0+rev2-standalone` - however the images downloadable from resinos.io are actually named like `resinOS 2.9.6+rev1.dev`.
Are the image names on resinos.io "incorrect", is the documentation at https://docs.resin.io/understanding/understanding-devices/2.x/#variants-of-resinos incorrect, or am I just misunderstanding things?

**Comment by shaunmulligan** [comment]
@lurch the docs are incorrect, I think I wrote most of that at 4am before we launched resinOS and we weren't sure what they naming was gonna be. Can you create a ticket on the docs issues?

**Comment by lurch** [comment]
Done @shaunmulligan :+1:
