### ISSUE TITLE
[website] Incorrect download links for Beaglebone Green images?

### ISSUE THREAD

**Issue by lurch** [resin-os/resinos#427]
While looking at https://resinos.io/#downloads-beaglebone I just noticed that the Beaglebone Green and Beaglebone Green Wireless are both linking to files in the `resinos/beaglebone-black/` directory. Should they instead be linking to images in the http://files.resin.io/?prefix=resinos/beaglebone-green/ and http://files.resin.io/?prefix=resinos/beaglebone-green-wifi/ directories?

**Comment by shaunmulligan** [comment]
@lurch, no those are the correct links. The BBB image is now a generic one that will work on all types. We are deprecating the others

**Comment by lurch** [comment]
Okay, cheers :)
(In that case I guess all three links ought to be pointing to the same version?)
