### ISSUE TITLE
ResinOS won't start | /dev does not exist

### ISSUE THREAD

**Issue by xbmcnut** [resin-os/resinos#452]
Hi there,

Don't know if this is the right place or not but seems resinOS related? I'm running Hass.io on Intel NUC that uses resin. After shutting down the NUC and plugging it back in, it won't boot and I get this on the screen

`root '/dev/disk/by-label/resin-rootA' doesn't exist or does not contain /dev`

Is that something I can debug if I look through the contents of the boot drive?

**Comment by LeighCurran** [comment]
I have the exact same problem after updating the supervisor . . .

**Comment by xbmcnut** [comment]
On NUC?

**Comment by LeighCurran** [comment]
Yeah, NUC, Hassio 65.X. I updated the supervisor to a newer version (I can’t remember what the version numbers were now) and it didn’t boot back up.

**Comment by agherzan** [comment]
@xbmcnut Hello. In resinOS we can't reproduce this issue. Did you report this to hassio? Was this narrowed down as a resinOS issue? If so, could you provide steps on how to reproduce?

**Comment by xbmcnut** [comment]
@agherzan. Thanks for the reply. No feedback on their forums but I'll post on their GitHub page. Any thoughts on what is missing?

**Comment by agherzan** [comment]
Sadly no, I don't know what are the changes Hassio adds on top of resinos.

**Comment by LeighCurran** [comment]
Got nothing from Hassio forums. The reason I posted here is because I thought that /dev/disk/by-label/resin-rootA is a partition or similar that ResinOS is trying to boot from, it's the first screen you see after POST so I assumed it was OS related. Does anyone know if I'm on the right track?

**Comment by agherzan** [comment]
That is true. ResinOS uses a dual root partition design for host OS updates. rootA and rootB.

**Comment by xbmcnut** [comment]
I have lodged a bug report with Home Assistant.

**Comment by LeighCurran** [comment]
Does anyone know where the config file is for /dev/disk/by-label/resin-rootA ? I assume the fix is going to be to point back to RootB?

**Comment by agherzan** [comment]
grub.cfg in the boot partition.

**Comment by LeighCurran** [comment]
I managed to try the rootA to rootB swap with no luck. Don’t happen to know how I can get to file located inside the docker container on a Windows box?
