### ISSUE TITLE
Find device MAC address

### ISSUE THREAD

**Issue by dakshshah96** [resin-os/resinos#462]
I've successfully setup and connected my Raspberry Pi device on the resin.io platform. I'm also able to access the Host OS terminal from resin.io.

How can I find out the MAC address of my Raspberry Pi Wi-Fi device from this terminal? I need this MAC address so I can whitelist it on my corporate Wi-Fi network.

**Comment by hpgmiskin** [comment]
Please take a look at [Finding the MAC Address of a Raspberry Pi](https://www.raspberrypi-spy.co.uk/2012/06/finding-the-mac-address-of-a-raspberry-pi/) which suggests that you can use the following command.

```
cat /sys/class/net/wlan0/address
```

**Comment by dakshshah96** [comment]
@hpgmiskin The MAC address of my Raspberry Pi running resinOS is different each time it reboots. This problem exists only with resinOS so I install Raspbian each time I need to determine the "permanent" MAC address of my device.

**Comment by agherzan** [comment]
@dakshshah96 what Board are you using? Do you see the random behaviour only on WiFi or does ETH behave similarly?

**Comment by dakshshah96** [comment]
@agherzan I'm using the Raspberry Pi 3 Model B.

So I just spawned a shell into my host OS from the resin.io dashboard and tried doing `ifconfig wlan0` multiple times. The issue seems to be resolved now.

Just a couple of weeks ago when I filed this issue, it'd show a random MAC address on each `ifconfig wlan0`. There was no such problem with `eth0`.

**Comment by agherzan** [comment]
Thanks for the update.
