### ISSUE TITLE
Images linked to in the download section on resinos.io are missing

### ISSUE THREAD

**Issue by peregrinator** [resin-os/resinos#463]
I haven't tried all the links but many aren't working...

For example the link for the Raspberry Pi 3 image is: https://files.resin.io/resinos/raspberrypi3/2.12.5%2Brev2/image/resin.img.zip

which returns:

![image](https://user-images.githubusercontent.com/22108/38514967-8d54e012-3be7-11e8-9b6e-bf914a799157.png)

**Comment by agherzan** [comment]
Hi @peregrinator . We currently test a fix for this. CC @zvin

**Comment by lurch** [comment]
When I go to resinos.io the Raspberry Pi3 download link is https://files.resin.io/resinos/raspberrypi3/2.12.5%2Brev2.dev/image/resin.img.zip which **does** work? :confused: 

Probably connects to #457

**Comment by agherzan** [comment]
@peregrinator @lurch It was due to a fixed we deployed today. As this is fixed now, I will close this issue.
