### ISSUE TITLE
Versioning and documentation

### ISSUE THREAD

**Issue by maciekrb** [resin-os/resinos#499]
Hey guys, 

I got a bit confused with the versioning, perhaps I'm missing something obvious here: 

[ResinOS documentation on camera configuration](https://docs.resin.io/learn/develop/hardware/i2c-and-spi/#raspberry-pi-camera-module) talks about `ResinOS 1.16.0`, `ResinOS 1.8.0`. On the other hand, I don't see such versions in the repo [CHANGELOG](https://github.com/resin-os/resinos/blob/master/CHANGELOG.md) or [RELEASES](https://github.com/resin-os/resinos/releases). 

To add to the confusion, when I add a device from the web console (and get the image download dialog) I get `ResinOS 2.15.1+rev2`. 

![screen shot 2018-09-26 at 10 40 10 pm](https://user-images.githubusercontent.com/484485/46108323-18eebe00-c1de-11e8-828e-50b216a5a42b.png)

Thanks in advance.

**Comment by ZubairLK** [comment]
@maciekrb resinOS v1.x is quite old while resinOS v2.x is newer.
The docs mentions ResinOS 1.16.0 or newer. resinOS v2.x is newer so I'd suggest trying that out.

Regarding changelog/releases: That is the docs/website repo. (Also named resinOS which I guess cause the confusion).

Look for changelog/release in meta-resin and in resin-raspberry
https://github.com/resin-os/meta-resin
https://github.com/resin-os/resin-raspberrypi

**Comment by maciekrb** [comment]
Thanks for clarifying !
