### ISSUE TITLE
Provisioning a device with deltas already enabled

### ISSUE THREAD

**Issue by resinio** [resin-os/resinos#508]
# Description 
Provisioning a device on an app that already has deltas pushed

# Steps to reproduce issue 
#### 1. Provision a device on the same app used for TC10
(that already has the RESIN_SUPERVISOR_DELTA=1 var and a pushed image).

#### 2. Push an update to the application
(for example, change what is outputted to the console).

# Expected result 
#### 1. The device should appear on the dashboard and correctly download the image for the app.
The application should run as expected.
Opening an app container web terminal should allow execution of commands.

#### 2. The dashboard logs should display: "Downloading delta for image ..."
The application update should be downloaded and then the updated app should be started.
Opening an app container web terminal should allow execution of commands.

# Actual result 
Didn't show any "delta" messages in dashboard:

25.10.18 17:27:44 (+0100) Downloading image 'registry2.balena-staging.com/v2/ba82b83f92ab1ae0229d5ec7b8bd9f92@sha256:585b52e226916d318993dd0676b59c68ba3bd49ff86279aba420945b96b8190d'
25.10.18 17:29:02 (+0100) Downloaded image 'registry2.balena-staging.com/v2/ba82b83f92ab1ae0229d5ec7b8bd9f92@sha256:585b52e226916d318993dd0676b59c68ba3bd49ff86279aba420945b96b8190d'

# Other information 
- Reported by: Andrei Gherzan 

- Test configuration: Balena Fin 

- Test case number: TC11 

- Test run: [https://resinio.testlodge.com/projects/16238/runs/332442?tab=2&run_section_id=482619#executed_case_14748958](https://resinio.testlodge.com/projects/16238/runs/332442?tab=2&run_section_id=482619#executed_case_14748958)

**Comment by resinio** [comment]
An associated test has been re-run in TestLodge. 

**Result:** Passed 

**Other information** 

- Update by: Andrei Gherzan 

- Test configuration: Balena Fin 

- Test case number: TC11 

- Test run: https://resinio.testlodge.com/projects/16238/runs/332442?tab=2&run_section_id=482619#executed_case_14748958

**Comment by agherzan** [comment]
It was a miss-read test case.
