### ISSUE TITLE
Add WiFi support over USB for vexpressa9 boards

### ISSUE THREAD

**Issue by agherzan** [resin-os/resinos#57]
_From @agherzan on July 4, 2016 10:45_

_Copied from original issue: resin-os/resin-fsl-arm#21_

**Comment by willnewton** [comment]
Vexpressa9 is an ARM Versatile Express platform (FPGA or QEMU-emulated) and Nitrogen6x is a iMX6 based development board. The original issue seems to have gone permanently so in the absence of any more information I don't think this issue can be progressed unless someone has a really good memory!
