### ISSUE TITLE
Move resolv.dnsmasq to resin-conf

### ISSUE THREAD

**Issue by agherzan** [resin-os/resinos#75]
_From @telphan on August 5, 2016 6:12_

_Copied from original issue: resin-os/resin-raspberrypi#42_

**Comment by telphan** [comment]
I do not think resolv.dnsmasq need to be persistent. I do not see any benefit for ResinOS if the nameservers in resolv/dnsmasq would be persistent over reboots.

**Comment by agherzan** [comment]
@telphan can you please write it here exactly how are these dns entries generated at this point and by what components? Just as documentation purposes and we will close this issue.

**Comment by telphan** [comment]
A networkmanager componet (i.e. resolvconf) will write the dns entries to /var/run/resolvconf/interface/NetworkManger. /etc/resolv.dnsmasq is a symlink to the above mentioned location. From here dnsmasq picks up the correct file via the symlink.
