### ISSUE TITLE
Install missing latest BT firmware for BBGW

### ISSUE THREAD

**Issue by agherzan** [resin-os/resinos#79]
_From @imrehg on September 2, 2016 17:6_

The latest BT firmware for BeagleBone Green Wifi seems to be using `TIInit_11.8.32.bts`, but we don't ship that. Since user applications can't very well pull in firmware (because of shadowing `/lib/firmware`, we should definitely install it. Also, it's almost 2 years old now. :)

Looks like the file has a number of different versions, the one installed from this repo appears to be working (done some device scanning as test, but that's all): https://github.com/rcn-ee/repos

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_lrx)

_Copied from original issue: resin-os/resin-beaglebone#33_

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_w3u)

**Comment by shaunmulligan** [comment]
@agherzan was this included in the latest releases?

**Comment by agherzan** [comment]
I don't think there was any work on this. @shaunmulligan

**Comment by shaunmulligan** [comment]
okay cool, no problem 👍

**Comment by imrehg** [comment]
Came up in the forums, as the previous workaround does not work anymore, since the resinOS 2.x rootfs is read-only: https://forums.resin.io/t/beaglebone-green-wireless-bluetooth/1784

**Comment by floion** [comment]
Created https://github.com/resin-os/resin-beaglebone/pull/116 for this

**Comment by floion** [comment]
PR merged. Closing this here as this will be available in the next release to production

**Comment by mesh0497** [comment]
I want to send data from my smartphone using some android application such as BlueTerm to my BeagleboneGreen Wireless. help me with your suggestions and codes.
