### ISSUE TITLE
Beaglebone uboot is sensitive to noise on UART0, might hang on boot

### ISSUE THREAD

**Issue by agherzan** [resin-os/resinos#80]
_From @imrehg on September 21, 2016 7:32_

Reported that BeagleBone Black uboot is sensitive to spurious noise on UART0 during boot, as noise might be interpreted as stop string.

See messages:
- https://groups.google.com/d/msg/beagleboard/aXv6An1xfqI/2_tLa7oWQBIJ
- http://lists.denx.de/pipermail/eldk/2014-June/002511.html
- also reported in support

The solution seems to be adjusting the uboot to be more resilient to noise, for example

```
CONFIG_AUTOBOOT_KEYED=y
CONFIG_AUTOBOOT_DELAY_STR="uboot"
```

or using the header files

```
#define CONFIG_AUTOBOOT_KEYED   1 
#define CONFIG_AUTOBOOT_DELAY_STR "uboot"
```

I guess the value of that string can be other values too, it's arbitrary just expect something. In the latest upstream u-boot there are some things like this implemented in uboot `defconfig` files since about the `v2015.07` release, and for BeagleBone specifically since `v2016.03` (current resin version seems to use `v2014.07`).

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_n8g)

_Copied from original issue: resin-os/resin-beaglebone#39_

**Comment by agherzan** [comment]
_From @BrianAdams on September 21, 2016 17:30_

This was the patch we added to fix the issue: https://github.com/BrianAdams/Bootloader-Builder/blob/fix/autoboot/patches/next/0003-Autoboot-keyboard-beaglebone-fixes.patch

**Comment by BrianAdams** [comment]
Also part of the analysis shows that the beaglebone reference u-boot project did add the condition that the character on the serial line has to be a " " which fixes the problem.
