### ISSUE TITLE
Apply memory pressure fix to 1.x release of Beaglebone boards.

### ISSUE THREAD

**Issue by shaunmulligan** [resin-os/resinos#88]
We currently have a fix for the Beaglebone Read-Only issues that we have seen in production, currently we apply this fix when users ask. We need to add this to all default downloads of resinOS, it should be applied to a 1.17 release of resinOS.

**Comment by agherzan** [comment]
@michal-mazurek can you please cherry pick the changes for this task on on top of 1.X branch too? We need it for the next 1.X release.
