### ISSUE TITLE
All resinOS 2.x builds should have uncompressed kernel modules.

### ISSUE THREAD

**Issue by shaunmulligan** [resin-os/resinos#89]
Currently the RPI and BBB family of devices have compressed kernel modules, this causes problems if people try to modprobe from with in their containers based on either Debian or Ubuntu.

**Comment by lurch** [comment]
Does this contradict with https://github.com/resin-os/meta-resin/issues/257 ?

**Comment by shaunmulligan** [comment]
@lurch yes, indeed it does. We are basically reverting all kernel module compression, because its become more problem than it is worth unfortunately 😢

**Comment by agherzan** [comment]
agherzan did close both with some explaination.

**Comment by agherzan** [comment]
@michal-mazurek can you please rebase https://github.com/resin-os/resin-raspberrypi/pull/57 on top of 1.X branch too? We need it for the next 1.X release.

**Comment by agherzan** [comment]
I meant cherry-pick

**Comment by agherzan** [comment]
@michal-mazurek same for https://github.com/resin-os/resin-beaglebone/issues/48
